### ISSUE TITLE
RESEACH [BUG]: Withdrawal of all supplied `MAI` left a rest

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#1007]
I tried to withdraw all supplied MAI in the following transactions, both of them left a rest in the market. It has worked for me with USDC and other markets before that. 

How could this be fixed?

https://polygonscan.com/tx/0x5c9d4596f5cae97d4875f741a242274ea078a9bad451163ca59c2c3e36afd0a9

https://polygonscan.com/tx/0xa49844015360e78d5764689d02b968ffe863e52ccfeea3e2a51f8f4e628ff60c

**Comment by vminkov** [comment]
We decided to leave this unresolved because the bug comes from rounding errors when calculating the liquidity and the possible changes to fix can lead to other bugs in the core accounting logic
