### ISSUE TITLE
Implement `StakedDotAPYProvider`

### ISSUE THREAD

**Issue by carlomazzaferro** [Midas-Protocol/monorepo#1020]
wstDOT has a base APY, which should be shown in the same way that the BNBx / stkBNB.

The API is this one: https://polkadot.lido.fi/api/stats/ (stDOT is the key to look for)

Sample response: 

```
~ ❯❯❯ curl -s https://polkadot.lido.fi/api/stats/ | jq .apr
13.012
```

**Comment by peetzweg** [comment]
Just fyi, `BNBx / stkBNB.` APY is hardcoded. Do we have an endpoint for this as well? Haven't search myself yet but can do. ✌️

**Comment by carlomazzaferro** [comment]
> Just fyi, `BNBx / stkBNB.` APY is hardcoded. Do we have an endpoint for this as well? Haven't search myself yet but can do. ✌️
 

> The API is this one: https://polkadot.lido.fi/api/stats/ (stDOT is the key to look for)

:)

**Comment by NikMidas** [comment]
Per @carlomazzaferro this has been completed
