### ISSUE TITLE
Show Reward Token of `CErc20PluginRewardsDelegate` Assets

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#103]
## Background

Once we have an Asset in the Pool which uses `CErc20PluginRewardsDelegate` as the contract it will will accrue rewards in it's flywheel. The other `CErc20PluginDelegate` does not have a flywheel.
We already show for both type of assets, that they are using a plugin. The reward token for the `CErc20PluginDelegate` is the Asset itself, so this does not have a reward token other than the asset itself, the APY is just increased.

`CErc20PluginRewardsDelegate` however, also accrues a Rewards token via it's flywheel or flywheels. 

On the localnode we have setup a plugin for `TRIBE` which is called `MockERC4626Dynamic`, which uses a flywheel which is deployed locally. You can find the configuration here:

https://github.com/Midas-Protocol/monorepo/blob/80b0afcef6505cb3aa265449a5d60bf702eef5c8/packages/sdk/chainDeploy/local/local.ts#L28-L52 

So we want to add the `TRIBE` Asset with the `MockERC4626Dynamic` Plugin and it should show the Reward Token of the `MockERC4626Dynamic` flywheel on the User Pool page.

## Definition Of Done

Reward tokens of `CErc20PluginRewardsDelegate` are shown on the Pool Page.

**Comment by Pczek** [comment]
Related to #20 #104
