### ISSUE TITLE
Claim Rewards from `CErc20PluginRewardsDelegate`

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#104]
## Background

#103 describes the `CErc20PluginRewardsDelegate` in a bit more detail. Users who have supplied this asset earn Reward Tokens, these need to be claimable by the user via the UI.

## Definition Of Done

As a user I can claim the rewards token earned by tokens supplied in a `CErc20PluginRewardsDelegate`.

**Comment by Pczek** [comment]
Related to #20

**Comment by peetzweg** [comment]
For future Reference:

Okay also bisher:
1) addStrategyForRewards braucht die strategy und nicht den cToken
https://github.com/Midas-Protocol/monorepo/blob/9d115091a886a69977b9f0fb82f7094fcd05e228/packages/sdk/src/modules/Asset.ts#L187-L189

2) accrue() wird mit strategy und user aufgerufen und nicht mit market & user
https://github.com/Midas-Protocol/monorepo/blob/9d115091a886a69977b9f0fb82f7094fcd05e228/packages/sdk/src/modules/Flywheel.ts#L130

3) Dieser Approval ist absoluter bullshit, allein die Eingabe parameter sind falsch.
https://github.com/Midas-Protocol/monorepo/blob/9d115091a886a69977b9f0fb82f7094fcd05e228/packages/sdk/src/modules/Asset.ts#L174-L180

Ein Approval müsste es aber dennoch geben, denn FuseFlywheelDynamicRewards will sich ja die rewardToken von der strategy an sich selbst schicken. 
https://github.com/fei-protocol/fuse-flywheel/blob/b1ebb618fe2965727d5a81d74d374a667a1e52b9/src/rewards/FuseFlywheelDynamicRewards.sol#L24-L28

Wie würde man diesen Approve machen? Kann ja nicht als  strategy  contract ein approve für die den FuseFlywheelDynamicRewards erteilen. 🤔

**Comment by carlomazzaferro** [comment]
Hey @peetzweg GH kann die Kommentare noch nicht übersetzen.  Aber ich verstehe, wir haben viel zu tun hier. @RedVeil help us lol

**Comment by peetzweg** [comment]
As we now have the new `Flywheels` deployed as `FuseFlywheelDynamicRewardsPlugin`. We need to add them to the jarvis pool and enable the strategies for them. Will do so tomorrow as I want to be available incase if something breaks doing so.

**Comment by peetzweg** [comment]
@RedVeil can you give input on point 3 in this comment: 
https://github.com/Midas-Protocol/monorepo/issues/104#issuecomment-1171477353

**Comment by peetzweg** [comment]
Next PR for fixing the broken setup: Reconfigure Pools with new flywheel:
https://github.com/Midas-Protocol/monorepo/pull/338
