### ISSUE TITLE
Abbreviate Token Symbols 

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#1055]
Some of the tokens we have in markets have extremely long token symbols. We should abbreviate them maybe at 5 characters and show the rest as a "tooltip" or simple 'title' tag on mouse hover.

It often breaks the ui unnecessarily.

A custom component which wraps the text in a `<span title={symbol}>{abbreviatedSymbol}</span>` could be a possible solution.

<img width="1031" alt="Screenshot 2022-11-25 at 09 36 45" src="https://user-images.githubusercontent.com/839848/203937493-f9b8ae99-6641-4b41-9334-e90f46f29c35.png">

**Comment by smartdevcom** [comment]
Fixed in this PR https://github.com/Midas-Protocol/monorepo/pull/1061
