### ISSUE TITLE
[BUG] Cannot see the claim button on xcDOT

### ISSUE THREAD

**Issue by veselod** [Midas-Protocol/monorepo#1069]
**Describe the bug**
User sees and receives wrong rewards for xcDOT pool. User deposited wstDOT, borrowed xcDOT and supplied to the xc DOT pool. Everything was working as is, until he supplied and later withdrew USDC.wh from the same pool. Now he can only claim LDO rewards in xcDOT pool (when it supposed to be just USDC). 

**To Reproduce**

Couldnt reproduce on my machine.

**Expected behavior**
Claim button for USDC rewards.

**Screenshots**
![photo_2022-11-30 20 00 26](https://user-images.githubusercontent.com/80520553/204873446-9860d3da-4ce3-4c20-80ba-a15f7db43e15.jpeg)

![photo_2022-11-30 20 00 22](https://user-images.githubusercontent.com/80520553/204873529-e8d3d8fb-f8f0-48e0-8b85-6385a1203cf8.jpeg)

**Context**
 - Chain: Moonbeam
 - Pool Id: stDOT Pool
 - Transaction Hash: https://moonscan.io/tx/0x4611322e88ee444de331ffee9e82f4eec1234c7475c6e8b2261cdb68c25db0fa
 - Error logs (screenshot): 

**Platform**
- Wallet used: MetaMask
- Mobile: [ ]

**Additional context**

**Comment by veselod** [comment]
Browser: Brave 1.46.133 Chromium: 108.0.5359.71 (64 bit)

logs:

inject.js:381 [yoroi/prod] dapp-connector is successfully injected into app.midascapital.xyz
celo-inpage.js:1 Uncaught ReferenceError: Web3 is not defined
    at r.default (celo-inpage.js:1:1495)
    at Object.<anonymous> (celo-inpage.js:1:1058)
    at 1../lib/setupWeb3.js (celo-inpage.js:1:1072)
    at i (celo-inpage.js:1:254)
    at e (celo-inpage.js:1:414)
    at celo-inpage.js:1:431
inpage.js:1 MetaMask no longer injects web3. For details, see: https://docs.metamask.io/guide/provider-migration.html#replacing-window-web3
get @ inpage.js:1
celo-inpage.js:1 CeloExtensionWallet: CeloExtensionWallet will soon stop reloading pages on network change.
For more information, see: https://docs.metamask.io/guide/ethereum-provider.html#ethereum-autorefreshonnetworkchange 
Set 'ethereum.autoRefreshOnNetworkChange' to 'false' to silence this warning.
(anonymous) @ celo-inpage.js:1
index.js:108 Irm JumpRateModel_JARVIS_2_004_4_08 not deployed to chain 56
(anonymous) @ index.js:108
index.js:115 Oracle CurveV2LpTokenPriceOracleNoRegistry not deployed to chain 56
(anonymous) @ index.js:115
index.js:108 Irm JumpRateModel_MIMO_2_004_4_08 not deployed to chain 137
(anonymous) @ index.js:108
index.js:108 Irm JumpRateModel_JARVIS_2_004_4_08 not deployed to chain 137
(anonymous) @ index.js:108
index.js:115 Oracle SimplePriceOracle not deployed to chain 1284
(anonymous) @ index.js:115
index.js:115 Oracle FluxPriceOracle not deployed to chain 1284
(anonymous) @ index.js:115
MultiMidasContext.tsx:118 LogRocket initialized
build.umd.js:3104 LogRocket: Session quota exceeded. Please upgrade your plan. Disabling ...
e.<computed> @ build.umd.js:3104
build.umd.js:3104 Manually updating APYs in Pool, fix me soon!
e.<computed> @ build.umd.js:3104
DevTools failed to load source map: Could not load content for chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/sourcemaps/inject.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://dmkamcknogkgcdfhhbddcghachkejeap/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://kkilomkmpmkbdnfelcpgckmpcaemjcdh/sourcemaps/celo-contentscript.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://kkilomkmpmkbdnfelcpgckmpcaemjcdh/sourcemaps/celo-inpage.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/sourcemaps/inpage.js.map: System error: net::ERR_BLOCKED_BY_CLIENT

**Comment by smartdevcom** [comment]
I couldn't reproduce this issue either.
And the point is that it seems not to be a UI issue because user actually claimed `LDO` from xcDOT`
https://discord.com/channels/930077813585899561/1046707087616507936/1047875036373061722

**Comment by veselod** [comment]
![photo_2022-12-08 19 33 37](https://user-images.githubusercontent.com/80520553/206523179-2fdedf8d-d234-435f-8e0e-afe0401f2cb9.jpeg)
![photo_2022-12-08 19 33 40](https://user-images.githubusercontent.com/80520553/206523202-a3bcb284-63fa-45c8-b091-fdf41d75402e.jpeg)
![photo_2022-12-08 19 33 42](https://user-images.githubusercontent.com/80520553/206523222-cf6b92f7-03c3-4ffd-83e2-55c6d86892cf.jpeg)
![photo_2022-12-08 19 33 46](https://user-images.githubusercontent.com/80520553/206523244-dc8f7159-0628-4c72-a951-117bd2873ab8.jpeg)
![photo_2022-12-08 19 33 49](https://user-images.githubusercontent.com/80520553/206523264-16e57fbc-b313-4788-891b-53cf94bad9d0.jpeg)

**Comment by NikMidas** [comment]
Resolved
