### ISSUE TITLE
[TRIAGE] Cannot perform action X

### ISSUE THREAD

**Issue by veselod** [Midas-Protocol/monorepo#1070]
**Describe the bug**
UI bug that shows the rewards APY x2

**To Reproduce**
1. Go to 'BNB pools'
2. Click on 'Jarvis jFIAT'
3. Scroll down to '2brl'

**Expected behavior**
See the APY rewards without the "doubling effect"

**Screenshots**
<img width="429" alt="Screenshot 2022-12-01 at 12 31 37" src="https://user-images.githubusercontent.com/80520553/205032415-c066a6e6-4a83-4814-9b19-d18d834e2f98.png">

**Context**
 - Chain: BNB
 - Pool Id: Jarvis jFIAT
 - Transaction Hash: 
 - Error logs (screenshot): 

**Platform**
- Wallet used: 
- Mobile: [ ]

**Additional context**
No additional comments, screenshot is self-explanatory.

**Comment by smartdevcom** [comment]
Fixed by @peetzweg 

The issue seemed to be that the plugin data was not correctly hardcoded in the plugin.ts
https://discordapp.com/channels/930077813585899561/930157130454024192/1050031208811212822
