### ISSUE TITLE
Show Rewards End Date in the UI

### ISSUE THREAD

**Issue by NikMidas** [Midas-Protocol/monorepo#1073]
https://discord.com/channels/930077813585899561/1046707087616507936/1047881096005701765

Please the conversation from this link and below

**Comment by peetzweg** [comment]
I like this idea. Don't have an idea just yet how to combine `Rewards` and the information from the flywheel. Although, we maybe could adapt the FlywheelRouter/FlywheelLens to also spit out information about the length of the Static Rewards. 👍

**Comment by peetzweg** [comment]
https://github.com/fei-protocol/flywheel-v2/blob/5ac5d314362188e3ece31a9db7deba529f4e8cc7/src/rewards/FlywheelStaticRewards.sol#L17-L19
