### ISSUE TITLE
Show User Total Values in Pool Header

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#1082]
We should check which values we could show for the user in the pool view similar to euler. 
As of now we just show total values for the pool, which are nice but I guess a user is more interested in his own values as well.

![image](https://user-images.githubusercontent.com/839848/205631027-444a4375-5c9e-4da0-ba63-5594ca2eaec2.png)

- [ ] User Supplied
- [ ] User Bororwed
- [ ] User combined borrow rate (not sure how to calculate it yet, sync with @vminkov and or @RedVeil for input)
- [ ] User combined supply rate (same as borrow)

This should replace these components here:

<img width="1470" alt="Screenshot 2022-12-05 at 12 55 26" src="https://user-images.githubusercontent.com/839848/205631578-2171a524-0a82-448d-911c-d39e9983bd71.png">

**Comment by NikMidas** [comment]
Waiting for @peetzweg to review

**Comment by NikMidas** [comment]
@carlomazzaferro will be reviewing PR later today
