### ISSUE TITLE
Toggle Collateral Should Have a Modal Too

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#1093]
As activating and deactivating a market as collateral is changing the borrow limit of the user, is maybe isn't even possible if the user enters liqudidation range. We should show a proper modal like with the other Market operations withdraw,supply,borrow,repay with the updated values. If the colleratal is disabled/enabled.
Example of the Aave Modal. Ours should look the same as the other modals of us, except that the `AmountInput` is the Collateral Toggle.

<img width="1480" alt="Screenshot 2022-12-07 at 10 47 25" src="https://user-images.githubusercontent.com/839848/206145610-e444b478-a9e9-4a6d-81c3-e66402227d7c.png">

**Comment by NikMidas** [comment]
Resolved
