### ISSUE TITLE
Borrow Limit is not Increasing

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#1106]
Borrow Limit should increase
![demo](https://user-images.githubusercontent.com/839848/206735979-45804fb8-fa2c-4e07-ac3b-581bfd659acd.gif)

Borrow Limit should decrease

![demo](https://user-images.githubusercontent.com/839848/206736500-bc52c9f6-218d-451a-a14a-a4c481250673.gif)

**Comment by peetzweg** [comment]
Hotfix deployed:
https://github.com/Midas-Protocol/monorepo/commit/101808485b7f2a95712bce31576baa42cf3d9922

**Comment by peetzweg** [comment]
@smartdevcom does this hotfix break anything else related to the borrow slider?
https://github.com/Midas-Protocol/monorepo/commit/101808485b7f2a95712bce31576baa42cf3d9922

**Comment by smartdevcom** [comment]
Done by @peetzweg
