### ISSUE TITLE
RESEARCH: Optimize loading times for UI

### ISSUE THREAD

**Issue by NikMidas** [Midas-Protocol/monorepo#111]
Possible Solutions:
1) Custom backend
2) Optimize usage of Fuse Pool Lens
3) Better usage of the address provider contract

Research UI code and identify bottlenecks
Propose solution on how to speed up loading times

**Comment by NikMidas** [comment]
Haruto has completed the research phase of this item.  Will implement in a future release

**Comment by peetzweg** [comment]
Defined here:
https://www.notion.so/Custom-Back-end-Indexing-7ac96cf11bed49a593e5c133f40d0860
