### ISSUE TITLE
Show Supply Caps

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#1182]
We have the ability to change the supply cap for an asset in the admin UI. However this not shown in the UI for the user. We want to change that.

I asked @vminkov if we could add this data to the response of the Fuse Pool Lens as it's just another data field for each asset. But until than we probably need to fetch the data for each asset indidivually.

Regarding integration in the UI. We should add it to all elements which refer to the assets supply already. But only show this if the Asset Supply is limited.

Here is a small mockup what to change adapt if a asset has a Supply Cap.

<img width="1553" alt="Screenshot 2023-01-11 at 10 22 22" src="https://user-images.githubusercontent.com/839848/211769026-8e5c3f4c-e7bc-47a3-a4d0-2e0d5d7c9700.png">

**Comment by peetzweg** [comment]
Update: Veliko will add a function to the FusePool Lens to fetch all supply caps for a comptroller in one go. So we don't have 1 RPC request for each supply cap.
We can't add it to the existing fpl calls as we can't modify the return data without breaking anything.

**Comment by smartdevcom** [comment]
> Update: Veliko will add a function to the FusePool Lens to fetch all supply caps for a comptroller in one go. So we don't have 1 RPC request for each supply cap. We can't add it to the existing fpl calls as we can't modify the return data without breaking anything.

@vminkov if you added this fn and merged to development, then pls comment here or in discord with PR so that I will implemented this feature.

**Comment by vminkov** [comment]
> > Update: Veliko will add a function to the FusePool Lens to fetch all supply caps for a comptroller in one go. So we don't have 1 RPC request for each supply cap. We can't add it to the existing fpl calls as we can't modify the return data without breaking anything.
> 
> @vminkov if you added this fn and merged to development, then pls comment here or in discord with PR so that I will implemented this feature.

to be correct, the fn is for a single asset, not for a whole comptroller/pool

the name of the FPL fn is `getBorrowAndSupplyCapsForAsset`

**Comment by peetzweg** [comment]
> > > Update: Veliko will add a function to the FusePool Lens to fetch all supply caps for a comptroller in one go. So we don't have 1 RPC request for each supply cap. We can't add it to the existing fpl calls as we can't modify the return data without breaking anything.
> > 
> > 
> > @vminkov if you added this fn and merged to development, then pls comment here or in discord with PR so that I will implemented this feature.
> 
> to be correct, the fn is for a single asset, not for a whole comptroller/pool
> 
> the name of the FPL fn is `getBorrowAndSupplyCapsForAsset`

Can we split this function in two? One borrow caps and one supply caps?

But supply caps should return for all cTokens in the comptroller? 

We want to save on RPC requests, if we have to make 1 request for 1 ctoken, it's cumbersome and slow. It helps us if the data get's aggregated and returned by the FPL in one call.

If this can not be done for the borrow caps it's fine. We probably just show the borrow caps on demand anyways. But the supply cap is something we would always show for each market. Therefore it would be more resourceful to geht all supply caps in a single RPC eth_call call.

@vminkov

**Comment by vminkov** [comment]
> > > > Update: Veliko will add a function to the FusePool Lens to fetch all supply caps for a comptroller in one go. So we don't have 1 RPC request for each supply cap. We can't add it to the existing fpl calls as we can't modify the return data without breaking anything.
> > > 
> > > 
> > > @vminkov if you added this fn and merged to development, then pls comment here or in discord with PR so that I will implemented this feature.
> > 
> > 
> > to be correct, the fn is for a single asset, not for a whole comptroller/pool
> > the name of the FPL fn is `getBorrowAndSupplyCapsForAsset`
> 
> Can we split this function in two? One borrow caps and one supply caps?
> 
> But supply caps should return for all cTokens in the comptroller?
> 
> We want to save on RPC requests, if we have to make 1 request for 1 ctoken, it's cumbersome and slow. It helps us if the data get's aggregated and returned by the FPL in one call.
> 
> If this can not be done for the borrow caps it's fine. We probably just show the borrow caps on demand anyways. But the supply cap is something we would always show for each market. Therefore it would be more resourceful to geht all supply caps in a single RPC eth_call call.
> 
> @vminkov

yes, I can split it, but it will return the supply caps for all markets in a pool in one call and the other will return the borrow caps in different calls for each market

**Comment by peetzweg** [comment]
Moved to production yesterday.
