### ISSUE TITLE
RESEARCH: Move Important Calculations from UI to SDK

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#12]
We have several calculations which would be better suited in the SDK Code.
We should research which calculations these are and bring them over into the SDK.

These new functions should be unit tested.

Unqualified suggestions
+ Borrow calculations
+ supply calculations
+ repay calculations
+ apy stuff?
+ borrow limits

**Comment by smartdevcom** [comment]
> useUpdatedUserAssets

Done with this PR https://github.com/Midas-Protocol/monorepo/pull/218

**Comment by smartdevcom** [comment]
> The `useUpdatedUserAssets` hook is a great candidate to add to the SDK itself to benefit from sharing this logic and test coverage.
> 
> https://github.com/Midas-Protocol/monorepo/blob/8d7dee9f772cc4462b20efb2f0ca6b1913af1c4b/packages/ui/hooks/fuse/useUpdatedUserAssets.ts#L10-L20

Done with this PR https://github.com/Midas-Protocol/monorepo/pull/218

**Comment by peetzweg** [comment]
Great 👍 
Let's close this for now and just open new tickets if we find more good candidates to pass over to the SDK.
