### ISSUE TITLE
Implement missing Liquidators

### ISSUE THREAD

**Issue by carlomazzaferro** [Midas-Protocol/monorepo#1216]
- [ ] Balancer LP Liquidator -> for MIMO/PAR BLP, WMATIC/stMATIC BLP, 2 BRL LP
- [ ] Saddle LPs Liquidator -> for StellaSwap stable LPs, saddle LPs on EVMOS and Arbitrum

**Comment by vminkov** [comment]
these are all liquidators only for the redemption of collateral, not the funding of debt, right?

**Comment by carlomazzaferro** [comment]
> these are all liquidators only for the redemption of collateral, not the funding of debt, right?

Correct. I'll need some help figuring out which funding strategies we need

**Comment by NikMidas** [comment]
Per Veliko, this is complete
