### ISSUE TITLE
Support Asset $MAI+val3EPS

### ISSUE THREAD

**Issue by carlomazzaferro** [Midas-Protocol/monorepo#122]
<h3> Custom Asset Information: </h3> <br>

*Use the reference below for Asset Information.  If not found in the table, please notify Nik via Discord* <br>
[Link to Notion Custom Asset Table](https://www.notion.so/4627d911ce3c4589aef9f7592650e7b2?v=4b3abb4ebfd44018bcf47496d512b778)

**Symbol**: **$MAI+val3EPS** <br>
**Block Explorer URL**:  *https://bscscan.com/address/0x80D00D2c8d920a9253c3D65BA901250a55011b37* <br>
**Chain**: *BSC*

*Please mark the tasks below, as appropriate.  Then link supporting Github items together using:* ![Screenshot of Github Link Button](https://user-images.githubusercontent.com/103433798/169572470-b7e31053-afab-4225-9816-6403193b86b3.png)

- [x] Requires Custom Oracle
  - [x] Requires `CurveLpTokenPriceOracleNoRegistry` to be configured, by adding the asset in the `curvePools` array in the `mainnet/bsc.ts` deployment script
- [x] Requires Custom Liquidator
  - [x] Requires `CurveLpTokenPriceOracleNoRegistry` to be configured, by adding the asset in the `curvePools` array in the `mainnet/bsc.ts` deployment script

<h3> Tasks: </h3>

- [x] Edit the supported assets:  https://github.com/Midas-Protocol/monorepo/tree/development/packages/sdk/src/chainConfig/assets and add the asset to the respective chain

- [x] Edit deployment script to set up and deploy oracle and liquidator

- [ ] Redeploy the fuse-twap-bot after adding editing the `supported_pairs` variable in the [ops directory](https://github.com/Midas-Protocol/monorepo/blob/development/ops/main.tf#L28)

*It does require custom liquidation strategy*
- [x] Edit the redemption strategies: https://github.com/Midas-Protocol/monorepo/blob/development/packages/sdk/src/chainConfig/redemptionStrategies.ts
- [x] Edit the redemption strategy data encoding: https://github.com/Midas-Protocol/monorepo/blob/development/packages/sdk/src/modules/liquidation/redemptionStrategy.ts#L23

*It needs use a plugin and flywheel*
- [ ] Edit the `chainDeploy/<chain>.ts` deploy script to deploy the Ellipsis4626 plugin
- [ ] Edit the `chainDeploy/<chain>.ts` deploy script to deploy  two flywheel(s): one for EPS rewards, one for VALA rewards

### Deployment

After all the items above are complete, proceed with the deployment of the contracts and changes to the deployment script. 

If a plugin and/or Flywheel were deployed with this, then, you also need to:
- [ ] Edit the plugin config: https://github.com/Midas-Protocol/monorepo/blob/development/packages/sdk/src/chainConfig/plugin.ts so that the information about it is made available to the SDK users/FE

**Comment by NikMidas** [comment]
Possible issue with Oracle for MAI, needs to be split up

**Comment by RedVeil** [comment]
PR https://github.com/Midas-Protocol/monorepo/pull/171
