### ISSUE TITLE
Show User Supplied and Borrowed Assets on Hover

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#1222]
Similar to total supplied and total borrows stat field, we want to show the users supplied and borrowed markets. At best all of them:

![demo2](https://user-images.githubusercontent.com/839848/214353628-72c4f6a2-8a80-4ea7-8dd1-5c2cc02ad1d2.gif)

**Comment by smartdevcom** [comment]
It should be shown. Maybe because you supplied or borrowed nothing?

![Peek 2023-01-25 10-20](https://user-images.githubusercontent.com/45715420/214451706-734c433a-8e08-432c-bae9-f4b269bba52a.gif)
