### ISSUE TITLE
Opening a Link in the Popover triggers Modal

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#124]
## Background

When opening a link via a popover, the element underneath it is clicked as well. Can we prevent this?

maybe event.preventDefault(), event.stopPropagation() etc.

![demo2](https://user-images.githubusercontent.com/839848/170959285-e65af414-8cca-4e85-a4a2-581aa069a1f7.gif)

## Definition Of Done

Clicking links in a popover only clicks inside the popover and not underneath it as well.

**Comment by smartdevcom** [comment]
Done PR https://github.com/Midas-Protocol/monorepo/pull/136
