### ISSUE TITLE
Change Network Loading Hiccup

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#125]
## Background

When loading the app for the first time on an unsupported network, the initial load of the pools fails. Maybe we are fetching the pools too early, before the actual switch to the new network has completed?

Step to reproduce:
1. connect to unsupported network in metamask => ethereum
2. reload a fresh copy of `app.midascapital.xyz` , => `CTRL+Shift+R`
3. switch to BSC mainnet via our modal
4. loading of pools should fail, refreshing the page or triggering a reload otherwise while connected to BSC succeeds.
=> Should succeed on the first try.

### Linked Issues & Documentation

![demo2](https://user-images.githubusercontent.com/839848/170963330-a8d504aa-6e6a-4c08-897a-14c3f11e462e.gif)

## Definition Of Done

This behaviour can not be reproduced and the loading of pools works fine even after switching the network.

**Comment by smartdevcom** [comment]
This issue seems to be related to changing network issue on wagmi.
![image](https://user-images.githubusercontent.com/45715420/171072508-de9d49af-2e9d-4cb5-999f-7ee41a9e33f7.png)
This issue also will be reproduced when switching between supported networks.
