### ISSUE TITLE
Resolve Metamask Error `-32603` in browser console

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#127]
## Background
`MetaMask - RPC Error: Internal JSON-RPC error.`

This error seems just recenlty filling up our UI console. We should resolve this.

<img width="632" alt="Screenshot 2022-05-30 at 18 08 48" src="https://user-images.githubusercontent.com/839848/171029419-7db084ce-a1ce-4d69-a342-a37ab0e0a111.png">

![unknown](https://user-images.githubusercontent.com/839848/171029271-0fc27f65-c813-4616-9322-3a4b166ea915.png)

### Linked Issues & Documentation

https://github.com/MetaMask/metamask-extension/issues/7286

## Definition Of Done

This error is resolved.

**Comment by smartdevcom** [comment]
This seems to be related to issues on function call for pools, but not sure where this happens

**Comment by peetzweg** [comment]
Okay I now know where this is comming from. Even though the exceptions are catched metamask will print them to the console... Ugly.

https://github.com/Midas-Protocol/monorepo/blob/cefb16257ac5217347f0fb2ccfa8ecde83246f54/packages/sdk/src/modules/FusePools.ts#L71-L72

**Comment by niraj-khatiwada** [comment]
I am having the same error
![image](https://user-images.githubusercontent.com/51436631/175825748-5b1a30de-9c98-4fab-a6fa-8c99243dbbff.png)

**Comment by peetzweg** [comment]
It an error logging we can't prevent. It's from metamask itself, however, we can make this section better:
https://github.com/Midas-Protocol/monorepo/blob/e0140a9fb65c5cdee6b30a243ba516dd51818cc8/packages/sdk/src/modules/FusePools.ts#L60-L80

We could check if the implementation address is a market which could potentially have a plugin. The error is caused by asking for a plugin of a market, which does not even have the field available.

**Comment by peetzweg** [comment]
Resolved in: https://github.com/Midas-Protocol/monorepo/commit/bd846b4cc6ad51d1fe60c83c6df58628e9a55ebf

This should boost pool data loading in general as well.
