### ISSUE TITLE
Retire Beefy plugins at EOL

### ISSUE THREAD

**Issue by vminkov** [Midas-Protocol/monorepo#1276]
BeefyAPYProvider: ellipsis-valdai3eps
Beefy Vault reach EOL status. Please check the vault: https://app.beefy.finance/vault/ellipsis-valdai3eps
BeefyAPYProvider: cakev2-wbnb-stkbnb
Beefy Vault reach EOL status. Please check the vault: https://app.beefy.finance/vault/cakev2-wbnb-stkbnb
BeefyAPYProvider: jarvis-2sgd
Beefy Vault reach EOL status. Please check the vault: https://app.beefy.finance/vault/jarvis-2sgd
BeefyAPYProvider: jarvis-2eurp
Beefy Vault reach EOL status. Please check the vault: https://app.beefy.finance/vault/jarvis-2eurp
BeefyAPYProvider: jarvis-2eur
Beefy Vault reach EOL status. Please check the vault: https://app.beefy.finance/vault/jarvis-2eur
BeefyAPYProvider: jarvis-2jpy2
Beefy Vault reach EOL status. Please check the vault: https://app.beefy.finance/vault/jarvis-2jpy2
BeefyAPYProvider: jarvis-2eurp
Beefy Vault reach EOL status. Please check the vault: https://app.beefy.finance/vault/jarvis-2eurp
BeefyAPYProvider: jarvis-2sgd
Beefy Vault reach EOL status. Please check the vault: https://app.beefy.finance/vault/jarvis-2sgd
BeefyAPYProvider: cakev2-wbnb-stkbnb
Beefy Vault reach EOL status. Please check the vault: https://app.beefy.finance/vault/cakev2-wbnb-stkbnb

TODO: what actions need to be taken? Emergency shutdown is the first step?

**Comment by vminkov** [comment]
@peetzweg let's transfer the discussion here

**Comment by peetzweg** [comment]
cc @carlomazzaferro

**Comment by carlomazzaferro** [comment]
0. Hot-fix frontend to show 0% APY for now
1. Emergency trigger to remove assets from vaults
2. Downgrade markets to normal CErc20Delegate
3. Continue supporting these markets w/o plugins


Are there any technical barriers here I am not aware of @vminkov ?

**Comment by vminkov** [comment]
> 0. Hot-fix frontend to show 0% APY for now
> 1. Emergency trigger to remove assets from vaults
> 2. Downgrade markets to normal CErc20Delegate
> 3. Continue supporting these markets w/o plugins
> 
> Are there any technical barriers here I am not aware of @vminkov ?

sounds good

**Comment by peetzweg** [comment]
> 0. Hot-fix frontend to show 0% APY for now
> 1. Emergency trigger to remove assets from vaults
> 2. Downgrade markets to normal CErc20Delegate
> 3. Continue supporting these markets w/o plugins
> 4. Remove all references to such plugins in the SDK codebase (security package / plugin config)
> 
> Are there any technical barriers here I am not aware of @vminkov ?

1. is in place since creation of this ticket ;) 

<img width="395" alt="Screenshot 2023-02-09 at 10 20 24" src="https://user-images.githubusercontent.com/839848/217770412-496ba708-4f6d-4551-bf17-f88a0230a253.png">
