### ISSUE TITLE
FusePoolsPage does not show Correct Borrow and Supply Values

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#128]
<img width="943" alt="Screenshot 2022-05-30 at 18 22 04" src="https://user-images.githubusercontent.com/839848/171031154-482fbc58-2390-4b62-9794-276fefb1ce77.png">

**Comment by smartdevcom** [comment]
Done https://github.com/Midas-Protocol/monorepo/pull/133
