### ISSUE TITLE
Ankr on BNB

### ISSUE THREAD

**Issue by NikMidas** [Midas-Protocol/monorepo#1286]
1) Add a Flyhwheel for ANKR on BNB ( 0xf307910a4c7bbc79691fd374889b36d8531b08e3) @peetzweg/ can probably take care of this ( we also need a feed for the frontend)"

**Comment by NikMidas** [comment]
@carlomazzaferro Need a price oracle for Ankr token on BNB

**Comment by carlomazzaferro** [comment]
> @carlomazzaferro Need a price oracle for Ankr token on BNB

We already have this

**Comment by peetzweg** [comment]
Than everything should work fine distributing ANKR rewards on BNB through a flywheel. ✅
