### ISSUE TITLE
Implement APYProvider for HAY plugin

### ISSUE THREAD

**Issue by carlomazzaferro** [Midas-Protocol/monorepo#1293]
Pool: https://development.midascapital.xyz/56/pool/16
Market: https://bscscan.com/address/0xAB7d4760E2c54c0Da1efEC7C358F171d72e14153
Strategy: https://bscscan.com/address/0x369ddC01E8feF7350Eb740f4a32647E8640F0A17

For the HAY plugin on the Helio pool, no API exists, but their devs pointed us to this code to make it work:

```
        const SECONDS_IN_YEAR = new BigNumber(31536000);
        export const HUNDRED = new BigNumber(100);

        const sdk = await ContractsManager.getInstance();
        const contract = await sdk.getJarContract();

        const [staked, rewards, rate, totalSupply, rawBalance] =
          await Promise.all([
            contract.methods.balanceOf(currentAccount).call(),
            contract.methods.earned(currentAccount).call(),
            contract.methods.rate().call(),
            contract.methods.totalSupply().call(),
            dispatch(
              getLoanTokenBalance.initiate(undefined, {
                subscribe: true,
                forceRefetch: true,
              }),
            ),
          ]);

        const { data: balance } = rawBalance;
        const totalDeposit = convertFromWei(totalSupply);

        const APR = new BigNumber(convertFromWei(rate))
          .multipliedBy(SECONDS_IN_YEAR)
          .div(totalDeposit)
          .multipliedBy(HUNDRED);
```

JAR contract address: `0x0a1Fd12F73432928C190CAF0810b3B767A59717e`

**Comment by peetzweg** [comment]
@carlomazzaferro can you get me in contact with the Helio team.

I'm not to sure how to obtain the `rawBalance`. They are calling a `getLoanTokenBalance.initiate` function, which is not described in the snippet.


```ts
dispatch(
  getLoanTokenBalance.initiate(undefined, {
    subscribe: true,
    forceRefetch: true,
  }),
),
```

**Comment by carlomazzaferro** [comment]
> @carlomazzaferro can you get me in contact with the Helio team.
> 
> I'm not to sure how to obtain the `rawBalance`. They are calling a `getLoanTokenBalance.initiate` function, which is not described in the snippet.
> 
> 
> ```ts
> dispatch(
>   getLoanTokenBalance.initiate(undefined, {
>     subscribe: true,
>     forceRefetch: true,
>   }),
> ),
> ```

Added you
