### ISSUE TITLE
Mobile UI Looks broken

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#1306]
![IMG_6174](https://user-images.githubusercontent.com/839848/221157356-7234d424-8514-432f-afd6-68f3eae37fb6.PNG)
![IMG_6173](https://user-images.githubusercontent.com/839848/221157371-0bb34c62-3bec-4e83-a579-19c4b16840b5.PNG)
![IMG_6172](https://user-images.githubusercontent.com/839848/221157378-c6dcb8b4-0689-40d3-ac82-fec03ec385e5.PNG)
<img width="686" alt="Screenshot 2023-02-24 at 11 10 38" src="https://user-images.githubusercontent.com/839848/221157460-705cbe25-23d8-4648-a219-9de7e4a49480.png">
<img width="634" alt="Screenshot 2023-02-24 at 11 14 55" src="https://user-images.githubusercontent.com/839848/221157468-aef8f642-9029-4be8-b72e-2ea7bf7453df.png">

**Comment by smartdevcom** [comment]
Already fixed mobile style
