### ISSUE TITLE
Allow Opening Links in Tabs

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#1309]
It's pretty annoying that almost none of our links can be opened in tabs.

We had this before a bit but had issues with everything reloading if we are not using javascript to redirect. There has to be a valid way to do this.

Account page and individual Pools would be great to open in new tabs.

<img width="578" alt="Screenshot 2023-02-28 at 09 47 48" src="https://user-images.githubusercontent.com/839848/221801032-1bb1d815-aa04-4c45-9e6f-4a5bfe8d326a.png">

<img width="1036" alt="Screenshot 2023-02-28 at 09 47 53" src="https://user-images.githubusercontent.com/839848/221801413-b4491e77-901e-434d-8d8d-7ee8cec53fa6.png">

**Comment by smartdevcom** [comment]
Regarding this feature, if we did link-able buttons, then loaded pages should be reloaded on click every time. So I am not sure we should go in this way. cc @carlomazzaferro

**Comment by carlomazzaferro** [comment]
Probably not, I think this is just a very minor annoyance. Are there any workarounds?

> Regarding this feature, if we did link-able buttons, then loaded pages should be reloaded on click every time. So I am not sure we should go in this way. cc @carlomazzaferro

**Comment by smartdevcom** [comment]
I didn't find a way to open new page without reloading. I think this is impossible.

**Comment by carlomazzaferro** [comment]
I'll close this then
