### ISSUE TITLE
Increasing balance after repaying all

### ISSUE THREAD

**Issue by dezine2dev** [Midas-Protocol/monorepo#137]
## Background
- When we repay 50 out of 100 borrowed, next time max repay value is not 50. There is tiny difference.
- After we repay all, max withdraw value (= supplied value) is not original value. 
In video it is 400 originally but it is also changed

https://www.loom.com/share/ec6c584396744265b8f1b57cf2ce8b0b

**Comment by peetzweg** [comment]
Yes that is correct. We have to pay a interest on the borrow amount. So if you borrow 100 TOUCH for a few blocks you have to pay interest for these blocks i.e 101 TOUCH.

On the supplier side you earn interest by supplying your Touch to be borrowed. So if TOUCH has been borrowed the interested paid by the borrowers will be the earnings of the supplier side, so the supplier gets more TOUCH out as he put in, start 400 TOUCH and later 401 TOUCH.


The main issue is that when repaying the "MAX" button wasn't setting the value high enough to repay all borrows of that token to the full extend. So when getting 100TOUCH we have to repay 101 TOUCH, but the max button was just setting it to 100 TOUCH. So we still had to pay 1 TOUCH more. This is the bug described in #25 .

**Comment by peetzweg** [comment]
fixed
