### ISSUE TITLE
Replace Loading Animation

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#138]
## Background

Our current loading animation is off the shelf and reminds the user of an unpolished porjects as well as market.xyz, we want to further break these ties by having a custom loading animation.

One idea we had about this was to use this circle graphic from the landing page. Maybe a simple spin would do the trick for now.

<img width="1426" alt="Screenshot 2022-05-31 at 10 05 24" src="https://user-images.githubusercontent.com/839848/171124135-e0c9c21d-7a76-4a8e-8af8-7784ca9c394b.png">

### Linked Issues & Documentation

We should use Framer Motion for this, it's used by chakra ui already.
https://www.framer.com/docs/examples/

## Definition Of Done

We replaced all our stock loading animations with our custom one.

**Comment by peetzweg** [comment]
This is the graphic we want to use as SVG. 
Haven't used framer myself, yet. A simpel rotation animation with a easing function would do it for now.

It should replace all the react-spinner uses and also the hash loading animation from chakra in the AmountSelect modals.

![circles](https://user-images.githubusercontent.com/839848/171259267-dc54e283-8f69-4532-8df3-442d7e338caf.svg)

**Comment by smartdevcom** [comment]
Done with PR https://github.com/Midas-Protocol/monorepo/pull/148
