### ISSUE TITLE
Platform Fee is stated as zero

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#146]
## Background

We at Midas have a general Platform fee, which is shown in the Pools Details, it's seems to be zero on BSC Mainnet. Afaik this is not true? 

<img width="1030" alt="Screenshot 2022-06-01 at 09 42 51" src="https://user-images.githubusercontent.com/839848/171353870-dee28464-6216-4b4e-abc9-0adbe0f94d4e.png">

## Definition Of Done

We show the correct Platform Fee.

**Comment by peetzweg** [comment]
Were we able to resolve this @dezine2dev

**Comment by carlomazzaferro** [comment]
close in favour https://github.com/Midas-Protocol/contracts/issues/266
