### ISSUE TITLE
RESEARCH: Rework `useRSS` Hook

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#174]
```
// TODO REWORK
// duplicated code from useFusePoolData and it's not even needed!!
// RSS should be able to be calculated completly in the backend.
// Quite ridiculous to fetch usd prices and pool data in frontend to just pass it to the backend...

```

## Background

Any information that gives more context as to why this task exists, and why it matters. This might include: links to discussions, documentation, or other Jira issues / tasks

### Linked Issues & Documentation

- List of linked issues, external links, etc

## Definition Of Done

Describes in 1-2 sentences what the output of the Task is, so that it can be verified by another team member easily. “Feature X is implemented as described and can be verified by using it”

## Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

**Comment by smartdevcom** [comment]
Shouldn't `RSS` calculation be moved to SDK? cc @peetzweg

**Comment by peetzweg** [comment]
This first code portion is very similiar and would be good to remove duplicated code:

https://github.com/Midas-Protocol/monorepo/blob/1bd5d1ab26ba57f5167dec6cfde7582e4e52d25c/packages/ui/hooks/useRSS.ts#L32-L61

https://github.com/Midas-Protocol/monorepo/blob/1bd5d1ab26ba57f5167dec6cfde7582e4e52d25c/packages/ui/hooks/useFusePoolData.ts#L24-L55
