### ISSUE TITLE
UI: Pools load properly only after manual refresh

### ISSUE THREAD

**Issue by NikMidas** [Midas-Protocol/monorepo#181]
**Describe the bug**
Initial page load for app.midascapital.xyz gives a pool error.  Once manually reloaded, the pools show up properly again

**To Reproduce**
1. Go to app.midascapital.xyz
2. Pools will not load correctly, hit refresh to see the page load correctly.

**Expected behavior**
Pools should load correctly on initial laod

**Screenshots**
Before:
![2022-06-06 at 1 53 PM](https://user-images.githubusercontent.com/103433798/172228049-954eb645-db0d-44f7-a653-daf5ad5c9c8d.png)

After:
![2022-06-06 at 1 56 PM](https://user-images.githubusercontent.com/103433798/172228154-c9784ef0-5c2d-4fdb-ad17-ed99f667e417.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by peetzweg** [comment]
Sounds quite similar to this one
https://github.com/Midas-Protocol/monorepo/issues/125
