### ISSUE TITLE
Ability to name cToken with custom names in UI and Contracts

### ISSUE THREAD

**Issue by NikMidas** [Midas-Protocol/monorepo#185]
Ankr requested this, per Dom

**Comment by peetzweg** [comment]
Renaming is impossible, naming them during deployment is straight forward.
We set the name ourselves for now but adding an input for users to give the vault token a name can be done in a day.

**Comment by NikMidas** [comment]
Will need to talk to Ankr again to see if this is something that they are wanting this still

**Comment by peetzweg** [comment]
Done
