### ISSUE TITLE
Figure Out How to Use the UI with BSC Mainnet Fork

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#19]
## Background

> As a Developer I want to use the local forked version of BSC with the UI

How can we use the local forked version of BSC with the UI + MetaMask, this would help a lot in development.

**Comment by adub671** [comment]
I confirmed and verified that these instructions are working: https://www.notion.so/Use-the-UI-with-a-Mainnet-Fork-c34ef2ff701b4f268287276d3f3f0550

also added instructions for windows users as it was slightly different.

**Comment by smartdevcom** [comment]
Could you create a pool on BSC forked? cc @adub671

**Comment by adub671** [comment]
@smartdevcom 

![image](https://user-images.githubusercontent.com/20121070/189229525-9435d12e-0dcf-474c-b880-5644cadb57cf.png)

per Veliko it works on [app.](https://app.midascapital.xyz/) but not on a local version

I just tried on a local version but was unable to access the app; however, was able to on production version

![image](https://user-images.githubusercontent.com/20121070/189230618-117eb6c6-962d-4c98-9184-ac37f3dcc77f.png)
