### ISSUE TITLE
Remove build outputs from source code, generating them in the UI build process

### ISSUE THREAD

**Issue by carlomazzaferro** [Midas-Protocol/monorepo#194]
We are currently storing in git the outputs from `forge build` in `contracts`, mostly for legacy reasons: in Vercel, it was not possible to run the forge commands appropriately. Now that we are using Netlify, we can use Netlify Manual deploys: https://docs.netlify.com/cli/get-started/#manual-deploys

To generate the build outputs with forge, removing their need to be stored in git in `contracts`

**Comment by peetzweg** [comment]
https://github.com/Midas-Protocol/monorepo/pull/196
