### ISSUE TITLE
Error: must have at least one chain

### ISSUE THREAD

**Issue by smartdevcom** [Midas-Protocol/monorepo#211]
## Background

We are getting an error `Error: must have at least one chain` while building UI. Because we are using only non-built chains on wagmi.
Already opened discussion on wagmi channel https://github.com/tmm/wagmi/discussions/578 and we need to wait for their reply

![image](https://user-images.githubusercontent.com/45715420/173586462-42a5016f-5124-4c5a-aae2-d7874bcba57f.png)

## Definition Of Done

CI for building UI should be success

**Comment by peetzweg** [comment]
But why do builds on `development` work? Shouldn't they break as well? 🤔

**Comment by smartdevcom** [comment]
> But why do builds on `development` work? Shouldn't they break as well? thinking

I am not sure why
