### ISSUE TITLE
ASSET SUPPORT: New Assets to Support Per Convo with James Key

### ISSUE THREAD

**Issue by NikMidas** [Midas-Protocol/monorepo#213]
USDT-WBNB 0x16b9a82891338f9ba80e2d6970fdda79d1eb0dae
USDC-WBNB 0xd99c7f6c65857ac913a8f880a4cb84032ab2fc5b
USDC-ETH 0xea26b78255df2bbc31c1ebf60010d78670185bd0
BUSD-BTCB 0xf45cd219aef8618a92baa7ad848364a158a24f33

**Comment by carlomazzaferro** [comment]
Completed
