### ISSUE TITLE
Setup Basic End to End UI Tests with Cypress

### ISSUE THREAD

**Issue by carlomazzaferro** [Midas-Protocol/monorepo#22]
## Background

Set up automated e2e tests to ensure the PRs aren't breaking flows 

### Linked Issues & Documentation

NA

## Definition Of Done

CICD runs e2e tests with Cypress

## Tasks

- [ ] Implement test scaffolding
- [ ] Implement CI flow

**Comment by peetzweg** [comment]
We should give it a retry now and follow the examples of synpress closely. 

https://github.com/Synthetixio/synpress


We should try to copy the setup from these examples mentioned. They look well thought out. 
Would be great if we could have a similar setup.

> For usage examples, feel free to take a look at [kwenta](https://github.com/kwenta/kwenta/tree/master/tests/e2e), [staking](https://github.com/Synthetixio/staking/tree/master/tests/e2e) or [synpress](https://github.com/Synthetixio/synpress/tree/master/tests/e2e) repository.
