### ISSUE TITLE
Implement ERC4626 APY Tracking Spec

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#221]
## Background

@RedVeil came up with a specification on how we could potentially track the APRs of our ERC4626 vaults. We need to decide on the step forward on this and implement it in a reasonable way.

Probably needs a sync meeting with @carlomazzaferro @RedVeil and @peetzweg .

### Linked Issues & Documentation

https://www.notion.so/ERC4626-APY-Tracking-Spec-09258b649cf44421afab87fc0edbd165

#170

## Definition Of Done

We have somehow access to the current and at best historic APR of a ERC4626 Vault and it's Plugin earnings.

**Comment by carlomazzaferro** [comment]
https://github.com/Midas-Protocol/monorepo/issues/312
