### ISSUE TITLE
Available liquidity is incorrect

### ISSUE THREAD

**Issue by carlomazzaferro** [Midas-Protocol/monorepo#228]
For bomb pool, available liquidity should be zero, because out of the borrowable assets, only BTCB has available liquidity, and its liquidity is effectively zero (all of it is borrowed)

![Image](https://user-images.githubusercontent.com/9201443/174130235-026a4caf-9ab8-44c2-8c12-4936e1d1f0f2.png)

**Comment by peetzweg** [comment]
Done https://github.com/Midas-Protocol/monorepo/pull/229
