### ISSUE TITLE
Enable Creation of Borrow Flywheel

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#23]
## Background

> As a User I want to be able to create a flywheel which rewards the borrow side of a market.

In order to do this we need to deployed this new FuseFlywheelBorrow contract with StaticRewards and a particular Booster contract.

## Related Code:
https://github.com/fei-protocol/fuse-flywheel/pull/10

## Definition Of Done

Flywheel can be created and managed by the owner, updating the RewardInfos.

**Comment by vminkov** [comment]
> Still blocked by merge: [fei-protocol/fuse-flywheel#10](https://github.com/fei-protocol/fuse-flywheel/pull/10)

not blocked anymore but we have implement our own in our repo, because we are using upgradable contract for the flywheels (with a performance fee)
