### ISSUE TITLE
`Create Pool UI` is Shaking

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#231]
## Background

When operating the sliders the UI for the creating a pool is shaking.

![demo2](https://user-images.githubusercontent.com/839848/174286835-c116cd9e-c090-4b1f-9e1e-693f8ccc0e19.gif)

## Definition Of Done

The Ui should not shake.

**Comment by peetzweg** [comment]
#230  could also be used here.

**Comment by smartdevcom** [comment]
done https://github.com/Midas-Protocol/monorepo/pull/252
