### ISSUE TITLE
UI: Progress Indicator when turning on collateral

### ISSUE THREAD

**Issue by NikMidas** [Midas-Protocol/monorepo#243]

**Comment by peetzweg** [comment]
Totally agree, we even have something like this already implemented in the UI. However, it's not yet used everywhere as the solution is not yet versatile enough to be used for every tx, especially with the sdk. But we are working on it.

For reference, the old ticket:
https://github.com/Midas-Protocol/midas-ui/issues/158 Maybe we can start a new ticket to mentioned most cases we want to have this. (Pool Creation, basically every big sdk interaction would be hard and we need to resolve other tickets first)

Using a service like blocknative as Rahul suggested could be a interesting! Will look into that. Not sure what kind of services they offer, but could see a third party service working for this as well.
