### ISSUE TITLE
Not Repaying Enough

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#25]
## Background
> As a User, when I repay the MAX amount, i expect I've repaid everything i'd owed.

See demo, below. I borrowed 1 TOUCH and repaid the loan by pressing `MAX`, however, it was not enough to close the borrow position. The position had some TOCUH to repay left, even if it's very small, I can always repay more and more touch. After a few repayments the position is finally repaid.

![demo2](https://user-images.githubusercontent.com/839848/166701530-8fc8595f-7a3e-410c-ad05-9d3179b0a72a.gif)

## Definition of Done

My owed balance can be repaid in one go via the `MAX` amount button.

**Comment by Pczek** [comment]
Yes that's kind of correct. You have to pay interest on your borrow, so you have to pay 10 TRIBE + interest. So just 10 TRIBE won't resolve your borrow position.
Try to repay the 10 TRIBE. After you repayed the 10, you can open the modal again and press again on MAX, to see you still have some open borrow balance. 
This can be continued a few times before the actual borrow amount has been repaid.
