### ISSUE TITLE
Issue withdrawing the 2brl LP

### ISSUE THREAD

**Issue by NikMidas** [Midas-Protocol/monorepo#259]
Darrell came across an issue with withdrawing the max amount in 2BRL LP.

![Image](https://user-images.githubusercontent.com/103433798/174607179-04bf1048-3d69-4047-a90d-0d055fe188f8.png)

TXN: https://bscscan.com/tx/0x4df2d43f200a109398e6482b9c698ec8538c6656c75c3aa6625d063153f716fb

**Comment by smartdevcom** [comment]
![image](https://user-images.githubusercontent.com/45715420/177959730-f4732314-21c7-45aa-a2ee-63c1753e3472.png)

I can withdraw max value now

**Comment by NikMidas** [comment]
We have another issue open regarding this item.  Closing this in favor of the other one.

**Comment by peetzweg** [comment]
https://github.com/Midas-Protocol/monorepo/issues/431
