### ISSUE TITLE
Show Midas Favicon in Metamask

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#26]
## Background

<img width="890" alt="Screenshot 2022-05-02 at 15 09 05" src="https://user-images.githubusercontent.com/839848/166246081-ce4a607c-f888-4570-bb17-621b5505aab4.png">

## Definition of Done

We have the midas app favicon also showing in metamask properly.

**Comment by Pczek** [comment]
Btw i think we issue before you had was related to an old `index.html` file we had in the code base. I removed it, it caused the errors we had with netlify...

So favicon stuff needs to be added in the `_document.ts` file using the Nextjs `<Head/>` component.

**Comment by peetzweg** [comment]
Does not even work on opensea, does not seem to be possible util we find a dapp which shows us otherwise.

<img width="1074" alt="Screenshot 2022-05-31 at 10 55 12" src="https://user-images.githubusercontent.com/839848/171134465-209dce01-e438-444c-8e4c-461b5a33e82c.png">

Good enough for now:
<img width="472" alt="Screenshot 2022-05-31 at 10 50 27" src="https://user-images.githubusercontent.com/839848/171134614-a81ff5fb-f7c1-46fb-a1e8-4734be996946.png">
