### ISSUE TITLE
Determine the correct calc utilization rate

### ISSUE THREAD

**Issue by NikMidas** [Midas-Protocol/monorepo#261]
![Image](https://user-images.githubusercontent.com/103433798/174683561-972b7978-2295-4f74-9767-0f1b425feb73.png)

**Comment by peetzweg** [comment]
Unfortunately, I can't find anything about the way how to calculate the utilization in the compound docs directly. However, this medium article makes a lot of sense and was referred to by @carlomazzaferro. 
Not so sure what `cash` and `reserve` values are in our case.

<img width="887" alt="Screenshot 2022-06-29 at 10 13 52" src="https://user-images.githubusercontent.com/839848/176386703-54fb7759-6ecb-4feb-a6e3-e1aa0d9b734d.png">

https://ian.pw/posts/2020-12-20-understanding-compound-protocols-interest-rates

**Comment by smartdevcom** [comment]
I think the calculation of `utilization` is right now.
Currently `utilization` is calculated by `asset.totalBorrow / asset.totalSupply`
https://github.com/Midas-Protocol/monorepo/blob/326d0bd000fb69ae82a53088aca6c9b2ac43e1c9/packages/sdk/src/modules/FusePools.ts#L111
And `asset.totalSupply` is getting like above formula in the screenshot 
https://github.com/Midas-Protocol/contracts/blob/e29b800ec0d89a57e3d3cc481c8bc7c44d125d6a/contracts/FusePoolLens.sol#L323-L326
So there seems not to be an issue with `utilization` calculation

**Comment by NikMidas** [comment]
Closing this item for now
