### ISSUE TITLE
UI: Set minimum borrow for each chain

### ISSUE THREAD

**Issue by NikMidas** [Midas-Protocol/monorepo#262]

**Comment by peetzweg** [comment]
How is this done via contracts? Can we only enforce this via the UI? Seems bad.

If we can do it via contracts which field can we use in the UI to give the information to the user.

**Comment by carlomazzaferro** [comment]
@peetzweg 

```
 function _setPoolLimits(
    uint256 _minBorrowEth,
    uint256 _maxSupplyEth,
    uint256 _maxUtilizationRate
  ) external onlyOwner {
    minBorrowEth = _minBorrowEth;
    maxSupplyEth = _maxSupplyEth;
    maxUtilizationRate = _maxUtilizationRate;
  }

```

This is called in the deploy script: https://github.com/Midas-Protocol/monorepo/blob/development/packages/sdk/deploy/deploy.ts#L61
