### ISSUE TITLE
Improve Pool Creation UX

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#31]
## Background

We want to guide the user transparently through all transactions necessary to create a new pool. Showing transaction by transaction progress and description of the current step.

<img width="1280" alt="Screenshot 2022-03-01 at 10 22 11" src="https://user-images.githubusercontent.com/839848/156144380-87a548c9-b2c7-4b52-8985-aecd404957b3.png">

<img width="1280" alt="Screenshot 2022-03-01 at 10 22 15" src="https://user-images.githubusercontent.com/839848/156144388-bb7dee67-b06f-4ad3-857f-19e4207be4c0.png">

**Comment by peetzweg** [comment]
Wasn't there another ticket which is more general? 
Nevertheless, I could imagine with javascript `generators` we could potentially implement a decent experience for developers & users.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator

**Comment by carlomazzaferro** [comment]
closing as we are keeping pool creation permissioned
