### ISSUE TITLE
Implement APY tracking spec

### ISSUE THREAD

**Issue by carlomazzaferro** [Midas-Protocol/monorepo#312]
As discussed in https://www.notion.so/ERC4626-APY-Tracking-Spec-09258b649cf44421afab87fc0edbd165 , we'll implement an off-chain storage system for calculating APYs over time. 

The system will have the following components:

- suapabase db, read-only from the internet, write only allowed by the cron job
- cron jobs run as cloud function https://docs.netlify.com/netlify-labs/experimental-features/scheduled-functions/ running 1 or twice a day (configurable)
- API that serves the data from the database 

Database structure:

```
depositAsset ⇒ plugin ⇒ depositAsset ⇒ [timestamp,pricePerShare]
              ⇒ plugin ⇒ depositAsset ⇒ [timestamp,pricePerShare]

depositAsset ⇒ plugin ⇒ depositAsset  ⇒ [timestamp,pricePerShare]

                        ⇒ flywheelAsset ⇒ [timestamp,pricePerShare]

                        ⇒ flywheelAsset ⇒ [timestamp,pricePerShare]
```

Cronjob: fetches `PricePerShare` and write into Supabase (Uses SDK for asset, plugin, flywheel configs)

Frontend: pulls last X elements from DB and calculates APY based on pricePerShareDelta

**Comment by peetzweg** [comment]
Here is a basic overview on how the mvp could look like with the current setup I prepared in #331 
<img width="1152" alt="Screenshot 2022-07-05 at 18 45 57" src="https://user-images.githubusercontent.com/839848/177377148-3f6f1ecf-0ace-4d4c-8031-89337fcc86f9.png">
