### ISSUE TITLE
Repurpose Test Pool into a valid pool; hide from UI until then

### ISSUE THREAD

**Issue by NikMidas** [Midas-Protocol/monorepo#364]
<ins>**Please describe the reasoning for this feature?**</ins> _Please mark one of the the checkboxes below, then put the description below that, screenshots preferred._ <br>
- [ ] _Is this to resolve a process problem, bug. defect, error or glitch?_ <br>
- [ ] _Is this for a new feature or improvement?_ <br>

We need to hide the test pools from the UI until we can repurpose them for valid ones
![2022-07-15 at 9 26 AM](https://user-images.githubusercontent.com/103433798/179244205-040f759d-7841-499c-9366-f0f62c314d8d.png)

<ins>**Describe the solution or new feature you'd like.**</ins>  _How can we improve our product?  What will bring more users to our protocol?_ <br>

<ins>**Describe alternatives that would satisfy requirements.**</ins> _What's an alternative that could satisfy the same requirements I was looking for?  Will it be harder?  Will it require more resources?._ <br>

<ins>**Additional context.**</ins> <br> _Any information that's relevant that doesn't fit in the categories above?_ <br>

**Comment by peetzweg** [comment]
so maybe a environment variable for each chain with comma separated pool ids?
