### ISSUE TITLE
Show APY from backend in for plugins and Flywheels

### ISSUE THREAD

**Issue by carlomazzaferro** [Midas-Protocol/monorepo#390]
FE follow up of https://github.com/Midas-Protocol/monorepo/issues/312

@coolnft can provide the endpoints and how to call the API

**Comment by NikMidas** [comment]
Here is what I think it should look like, and hopefully its the easiest way to do so:

a) Show the delta of the `PricePerShare` within a given timeframe.  Color code it to show red with minus or green with plus
b) Have a small info button that states what the timeframe of what the delta calculation is.

![Image](https://user-images.githubusercontent.com/103433798/180900979-9b089a00-eb0e-4f4f-9ab4-0a8edfed426f.png)

And possibly use this information box for other much needed info, similar to this

![Image](https://user-images.githubusercontent.com/103433798/180901407-543408c1-1f9b-4424-b127-902a8b644bf1.png)
