### ISSUE TITLE
UI: Moonbeam Rename XCM Pool and xDOT to xcDOT

### ISSUE THREAD

**Issue by NikMidas** [Midas-Protocol/monorepo#407]
Rename xPool to XCM Pool

![Image](https://user-images.githubusercontent.com/103433798/183984832-729fef5b-9d4d-4e45-9315-9c571b42e5ce.jpg)

Rename the asset from xDOT to xcDOT

Please rename the Moonbeam pool xDOT to xcDOT

**Comment by peetzweg** [comment]
Not relevant anymore. Misunderstanding:
https://discord.com/channels/930077813585899561/930157130454024192/1001881453723910205

**Comment by carlomazzaferro** [comment]
https://app.midascapital.xyz/1284/pool/1
