### ISSUE TITLE
Midas Logo is Shown for Mobile briefly on Initial Page Load

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#414]
See demo:
![demo](https://user-images.githubusercontent.com/839848/181511419-68764a1f-17ea-4c33-8358-e2bd2a3c8b0a.gif)

This should not happen. It worked at some point. Not sure which changes could have caused this.

**Comment by smartdevcom** [comment]
Done https://github.com/Midas-Protocol/monorepo/pull/419
