### ISSUE TITLE
Hardhat Cleanup Tasks

### ISSUE THREAD

**Issue by NikMidas** [Midas-Protocol/monorepo#430]
Per Carlo, let's limit the time we are taking to clean up.
1 hr to scope what needs to be cleaned up, 2 hrs to clean up.  Please document what has been cleaned up and what still might need to be done.

**Comment by peetzweg** [comment]
We have so many task for hardhat, some stuff might be outdated and not relevant anymore. Several files contain multiple tasks which is a bit confusing and hiding potential tasks which are still relevant:

<img width="586" alt="Screenshot 2022-08-02 at 15 47 43" src="https://user-images.githubusercontent.com/839848/182390509-1c7a82cf-fc14-4f03-b6d0-52d5ebde26e1.png">

**Comment by peetzweg** [comment]
We could probably remove more but for now it's easier to handle.
