### ISSUE TITLE
BUG:  Error 1004: Max Withdraw issue

### ISSUE THREAD

**Issue by NikMidas** [Midas-Protocol/monorepo#431]
Possible solution: using `.redeem`, instead of `.redeemunderlying` as the redeeming of the cTokens always results in a constant number of cTokens "cTokens do not accrue interest"

![Image](https://user-images.githubusercontent.com/103433798/182165646-ccfdb685-0117-4670-aade-dc2b1091fd0f.png)

![Image](https://user-images.githubusercontent.com/103433798/182165712-15479586-b2fd-4272-84e5-4821287a26ff.png)

**Comment by NikMidas** [comment]
Closing as this seems to be resolved now

**Comment by NikMidas** [comment]
Need to revisit this if its persistent and might need changes in the UI after PR has been merged and tested.  PLEASE DO NOT CLOSE UNTIL THIS HAS BEEN CHECKED AGAIN

**Comment by peetzweg** [comment]
This is unblocked and an UI only issue for now:


<img width="893" alt="Screenshot 2022-09-20 at 14 35 47" src="https://user-images.githubusercontent.com/839848/191259134-19175e9e-3068-4e74-a360-8a9f53026f1d.png">

`type(uint256).max`

https://github.com/Midas-Protocol/monorepo/blob/55d30a0847c731c9f4bba7a34752e9727b421671/packages/ui/utils/fetchMaxAmount.ts#L65-L82
