### ISSUE TITLE
List Pools from All Chains

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#464]
## Description

We want to improve the UX of Midas by showing all Pools of all chains instead of the only the pools of the current chain of the connected wallet.

We can't implement it yet in the SDK as our SDK is not yet working cross chain. Therefore we want to do it via API endpoints. These should be implemented in our ui nextjs app. The endpoints are lightly described in the `To Do` section of this ticket.

One more thing we should keep in mind and needs to be done, is that we need to refactor the URLs again. We need to make the them chain-agnostic. As of now we have these URLS
`https://app.midascapital.xyz/137?sortBy=supply` which include the chain. We need to get rid of it. We should convert it into a filter query `https://app.midascapital.xyz/?sortBy=supply&chain=137,56` and just show all chains pool if omitted.

Regarding the "Pool Details Page", we need to keep the URLs it was, as only the combination of the `chainId` and `poolId` uniquely identify a pool cross chain.
`https://app.midascapital.xyz/137/pool/1`

## To Do

- [ ] implement endpoint `GET /api/pools?chains=137,56` to return pool data from chain 137 and 56. If omitted return all data of pools form all supported chains
- [ ] use new `/api/pools` in UI

- [ ] implement endpoint `GET /api/tvl?chains=137,56` return tvl from requested chains. If omitted return all data of pools form all supported chains
- [ ] use new `/api/tvl` in UI

- [ ] update URL schema as described

**Comment by NikMidas** [comment]
Peet still working on this, much larger effort than originally thought

**Comment by smartdevcom** [comment]
PR https://github.com/Midas-Protocol/monorepo/pull/751
