### ISSUE TITLE
Defer Wallet Login Requirement on the Pool Overview

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#465]
## Description 

As of now, the first thing a user needs to do is to sign in with their wallet. This is fine but not a very good UX. With the completion of https://github.com/Midas-Protocol/monorepo/issues/464 we probably removed a lot of requirement for a wallet login from the pool overview page. 

The first step should be to make the requirement of a connected wallet optional for this Pool Overview Page. 

Next step would be to make it optional on the Pool Details Page as well. However, Overview would be fine for this ticket. We will create a follow up ticket.

**Comment by smartdevcom** [comment]
PR https://github.com/Midas-Protocol/monorepo/pull/751
