### ISSUE TITLE
Investigate Rewards Distributor so that it is configured to work cross-chain

### ISSUE THREAD

**Issue by carlomazzaferro** [Midas-Protocol/monorepo#47]
## Background

Investigate issues that might arise when using the compound contract in chains with different block times 

### Linked Issues & Documentation

- https://github.com/Midas-Protocol/contracts/blob/main/contracts/compound/RewardsDistributorDelegate.sol

## Definition Of Done

Documentation is produced

**Comment by peetzweg** [comment]
impossible
