### ISSUE TITLE
 Cache Nextjs Backend Calls

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#473]
We should add some caching for all our nextjs backend apis.

**Comment by peetzweg** [comment]
Netlify:

https://docs.netlify.com/integrations/frameworks/next-js/#limitations

Nextjs:

https://nextjs.org/docs/going-to-production#caching

**Comment by NikMidas** [comment]
Per team, this is something that can be closed for now since there isnt a great use case for it right now
