### ISSUE TITLE
Implement Price Oracle for MIMO

### ISSUE THREAD

**Issue by NikMidas** [Midas-Protocol/monorepo#476]
Waiting for DIA to respond back

**Comment by NikMidas** [comment]
Still waiting on them to provide the needed info

**Comment by carlomazzaferro** [comment]
https://forum.diadata.org/t/cdr-18-mimo-capital-asset-price/411

**Comment by peetzweg** [comment]
https://twitter.com/DIAdata_org/status/1576195284014604292
