### ISSUE TITLE
UI: Update Documentation Links for Strategies

### ISSUE THREAD

**Issue by NikMidas** [Midas-Protocol/monorepo#494]
Please update the following documentation links in the UI (each plug in the corresponding pool should have the same doc link):

**BSC**
Jarvis: https://docs.midascapital.xyz/guides/assets-and-strategies-addresses/binance-smart-chain-bsc/jarvis-jfiat-pool
BOMB: https://docs.midascapital.xyz/guides/assets-and-strategies-addresses/binance-smart-chain-bsc/bomb
Ellipsis: https://docs.midascapital.xyz/guides/assets-and-strategies-addresses/binance-smart-chain-bsc/ellipsis-x-dotdot

**Polygon**
Jarvis: https://docs.midascapital.xyz/guides/assets-and-strategies-addresses/polygon/jarvis-jfiat-pool

**Comment by smartdevcom** [comment]
PR https://github.com/Midas-Protocol/monorepo/pull/551

**Comment by smartdevcom** [comment]
We need to have public docs url for strategies and also there is something missing  for ellipsis pool in BSC cc @NikMidas

**Comment by NikMidas** [comment]
This one has been completed
