### ISSUE TITLE
UI: tooltip showing extra documentation of how to obtain an asset

### ISSUE THREAD

**Issue by carlomazzaferro** [Midas-Protocol/monorepo#505]
We'd like to have an UI tooltip that shows documentation of how to obtain it. This can be retrieving from the field `SupportedAsset.extraDocs`, implemented in this PR: https://github.com/Midas-Protocol/monorepo/pull/504

![Image](https://user-images.githubusercontent.com/9201443/184868627-940c480f-6a9d-480b-855d-5efa0f0853a8.png)

**Comment by smartdevcom** [comment]
Done https://github.com/Midas-Protocol/monorepo/pull/504/commits/4d524fd1f74dda21a201ae57ad058224ea14cf4e
