### ISSUE TITLE
Ability to import more granularly from the `chains` package

### ISSUE THREAD

**Issue by carlomazzaferro** [Midas-Protocol/monorepo#506]
For ui we need to make sure can import individual packages. Otherwise all the pages will just blow up with a 2.2MB chains packages.

We need to create multiple entry points to export more granular what we need.
https://nodejs.org/api/packages.html#package-entry-points

I tried that but wasn't able to finish it yet properly. It work in development but once building the ui it broke.

**Comment by peetzweg** [comment]
We may need to use a bundler in order to do this properly. Seems like quite hassle with plain typescript.

https://webpack.js.org/concepts/entry-points/

https://rollupjs.org/guide/en/
