### ISSUE TITLE
Alert Errors to Discord

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#518]
## Description 

We have several functions running in a scheduled manner via netlify functions.
We can read the logs in the netlify console. However, we are not actively checking if the functions succeeded.

In order to know if something failed, we want to pass the error to a discord channel similar to the `bot-alert` channel.

The functions currenlty scheduled are 
```
bsc-save-price
moonbeam-save-price
polygon-save-price
save-native-price
```
in the `packages/functions` package.

In the `catch` arm we should report the error to a discord channel probably called `functions-alerts`

https://github.com/Midas-Protocol/monorepo/blob/190d86c7c259d3eab93d7710a94c69891e8ad86e/packages/functions/src/controllers/flywheel.ts#L53-L55

Read up on the discord docs how to do this. 

https://discord.com/developers/docs/resources/webhook

**Comment by smartdevcom** [comment]
https://github.com/Midas-Protocol/monorepo/commit/d7fe272853e9e32a2613d268a7ba4a86406f5b64#diff-ab8f79b68b7adff7a07db953bf453f3c5aa6ade98d2b1b67d8432b36392489ed
