### ISSUE TITLE
Open External Links in New Window/Tab

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#541]
Make all links in these popovers open in new tab/window.
It's annoying to get back to midas capital as it reloads pretty long. Would be nice just to close th new tab/window once tokens are acquired.

<img width="540" alt="Screenshot 2022-08-22 at 10 15 04" src="https://user-images.githubusercontent.com/839848/185873114-4042f38f-d244-4820-8b46-fbfdc062d901.png">

**Comment by smartdevcom** [comment]
PR https://github.com/Midas-Protocol/monorepo/pull/554
