### ISSUE TITLE
Calculate the Reward Token APYs based on the Underlying Assets

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#543]
The current implementation of the apy data for "rewardToken" assets is giving an APY in the rewardToken itself. We need to convert it to the price of the underlying asset to give not confusing apys to users.

https://github.com/Midas-Protocol/monorepo/blob/5c7ec7c0ac5f3e72aaed03f6d0d60f0eb9e281d3/packages/ui/pages/api/apyData.ts#L68

We are missing price oracles for these assets: `DDD` and `EPX`.

**Comment by peetzweg** [comment]
We could probably show something like `1234 DDD / Block`. 🤷

**Comment by peetzweg** [comment]
We have this epic LensRouter which give us this info but only if we have a price oracle for the tokens.
https://github.com/fei-protocol/fuse-flywheel/blob/cd16a2ed23851d4158c4c98733afcea5db76cb13/src/FuseFlywheelLensRouter.sol#L47

**Comment by NikMidas** [comment]
Per Peet, this is complete
