### ISSUE TITLE
Investigate MIMO IRM

### ISSUE THREAD

**Issue by carlomazzaferro** [Midas-Protocol/monorepo#546]
MIMO irm's was deployed with these parameters: https://github.com/Midas-Protocol/monorepo/blob/development/packages/sdk/chainDeploy/helpers/irms.ts#L41

However, the IRM on the UI looks completely wrong: 

![Image](https://user-images.githubusercontent.com/9201443/185946252-fcfacb72-bb92-48a2-8c1c-9ae4c70823c1.png)

We should investigate why is this happening, ideally with a forge test to ensure the values coming out of the IRM are reasonable

**Comment by smartdevcom** [comment]
It seems like IRM looks correct on `Arrakis` and `Javis` pools but wrong in `MIMO` pool.
I guess `baseRatePerBlock` is too high for every asset in MIMO pool compared to assets in other pools.

`baseRatePerBlock`
MIMO - `0x22134fd13e`
Other pools - `0x71672e7f`

**Comment by peetzweg** [comment]
Deployed like this:
https://github.com/Midas-Protocol/monorepo/blob/development/packages/sdk/chainDeploy/helpers/irms.ts#L48-L57

Expected Result is:
https://docs.google.com/spreadsheets/d/1pOZ4Q3PYKtWBxBkNP7uzP0FIOeDHGcS8/edit#gid=51245992

**Comment by NikMidas** [comment]
Per Carlo, this can be considered done
