### ISSUE TITLE
UI: Lazy load pages instead of having multiple pages

### ISSUE THREAD

**Issue by NikMidas** [Midas-Protocol/monorepo#556]
We should show all pools in one page, instead of having a set amount per page

![Image](https://user-images.githubusercontent.com/103433798/186437922-28855d66-cd47-4566-bea6-aab22e61b36a.png)

**Comment by NikMidas** [comment]
Tasks needed to complete this task:

1) Implement correct view function for pool fetching

**Comment by NikMidas** [comment]
@vminkov completed the first part of this task.  @smartdevcom will connect with him on the rest of it

**Comment by smartdevcom** [comment]
https://github.com/Midas-Protocol/monorepo/issues/720 needs be resolved first

**Comment by peetzweg** [comment]
Not sure how well this ties into this cross chain topic.

https://github.com/Midas-Protocol/monorepo/issues/464

**Comment by peetzweg** [comment]
Not relevant anymore
