### ISSUE TITLE
Show balance of selected token in Modal.

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#559]
Show balance of selected token in Modal.

![Screen_Shot_2022-08-24_at_1 29 55_PM](https://user-images.githubusercontent.com/839848/186603031-b6e8c8d7-0568-4375-b192-aedbec199173.png)

**Comment by smartdevcom** [comment]
PR https://github.com/Midas-Protocol/monorepo/pull/560
