### ISSUE TITLE
'Your Supply' is not correctly Shown on Pool List Page

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#564]
<img width="773" alt="Screenshot 2022-08-26 at 11 52 58" src="https://user-images.githubusercontent.com/839848/186878929-952d7cc4-f377-4e73-af56-de1ef6102d1e.png">
<img width="822" alt="Screenshot 2022-08-26 at 11 52 49" src="https://user-images.githubusercontent.com/839848/186878934-a7199ac4-d050-4543-acf4-f0e63c29a34b.png">
alex

**Comment by smartdevcom** [comment]
PR https://github.com/Midas-Protocol/monorepo/pull/567
