### ISSUE TITLE
Optimize Usage of `/tokenData` endpoint

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#568]
We often return hardcoded data information, this can be easily resolved in the frontend directly. We should only fallback to the api if we don't have any data available for that token & chain id address.

Furthermore it would be handy if the api could resolve multiple tokens at once instead of a single token at a time.

**Comment by smartdevcom** [comment]
PR https://github.com/Midas-Protocol/monorepo/pull/573
