### ISSUE TITLE
Improve UX of Error Messages

### ISSUE THREAD

**Issue by NikMidas** [Midas-Protocol/monorepo#576]
We are showing the Raw Error to the user. We should handle the most common errors and make the error a bit less frightening to the users.

+ `Out Of Gas`
+ `User Rejected Transaction`
+ `Replacement Fee to Low`

Make sure to send the Error messages to LogRocket, we want to make better use of it now.

## Docs

Maybe this helps:
https://blog.logrocket.com/understanding-resolving-metamask-error-codes/

## Example

![demo](https://user-images.githubusercontent.com/839848/196891790-9ea3875f-67a9-4c1d-8a9b-fdeac61875bb.gif)

Looks super scary for users.

![IMG_0760](https://user-images.githubusercontent.com/839848/196896081-51cc9767-0138-4ac5-b00a-280c4b17077c.jpg)

**Comment by peetzweg** [comment]
We should not show the raw error, it should only be printed on the `console.error()` and send to LogRocket.

<img width="1365" alt="Screenshot 2022-10-20 at 14 39 06" src="https://user-images.githubusercontent.com/839848/196950799-d252bc0a-1f5b-4bb6-9729-f45ad7a625bc.png">
