### ISSUE TITLE
Ankr APY

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#580]
<img width="1274" alt="Screenshot 2022-08-31 at 13 45 52" src="https://user-images.githubusercontent.com/839848/187671262-e02dd1fb-eaff-409d-ba08-8b4663e06468.png">

https://discord.com/channels/930077813585899561/930157130454024192/1014500079064850493

https://bscscan.com/address/0xBb1Aa6e59E5163D8722a122cd66EBA614b59df0d#readProxyContract

![Screenshot_2022-08-31_at_13 40 38](https://user-images.githubusercontent.com/839848/187671307-84bb0914-5377-404d-8f47-76c00f384044.png)

<img width="1293" alt="Screenshot 2022-08-31 at 14 38 58" src="https://user-images.githubusercontent.com/839848/187680304-6eaae61e-8d68-4649-a85d-69b2b8e804fe.png">

<img width="875" alt="Screenshot 2022-08-31 at 14 14 47" src="https://user-images.githubusercontent.com/839848/187680314-ea616a84-9ced-43aa-8309-f3d6a5c0a128.png">

**Comment by carlomazzaferro** [comment]
https://www.ankr.com/docs/staking/liquid-staking/bnb/api/#get-apr

**Comment by smartdevcom** [comment]
PR https://github.com/Midas-Protocol/monorepo/pull/582
