### ISSUE TITLE
Hardcode `neon` price to 0.05 USD

### ISSUE THREAD

**Issue by carlomazzaferro** [Midas-Protocol/monorepo#592]
We'd like to have a functional UI for neon devnet. for that, we need to fetch realistic prices for it from Coingecko. Since it is not listed yet, we'd like to hardcode it to 0.05, as that is the rate that it goes for on the AMM on neon devnet: https://moraswap.com/exchange/swap

- [ ]: change cgId from `solana` to `neon`
- [ ]: hardcode the USD value, so that the UI shows reasonable values for collaterals

**Comment by smartdevcom** [comment]
PR https://github.com/Midas-Protocol/monorepo/pull/593
