### ISSUE TITLE
Don't Require a Connected Wallet to show Pool List

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#595]
Since the midas sdk now works without a signer as well, we can delay the required login to metamask to a later point and can already show the pools available in midas.

If easy it even pool details should be visible without a connected wallet. If tricky, require login once pool details are requested. => Follow up ticket for Pool details.

**Comment by carlomazzaferro** [comment]
closing in favour of https://github.com/Midas-Protocol/monorepo/issues/465
