### ISSUE TITLE
Fetch Pools from All Chains

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#596]
As we now have the capabilities to work with multiple instances of the midas sdk, we can fetch pools from all networks in the ui. 

Pools need to be marked with symbol to indicate the network they are operating on, similar too beefy.

https://app.beefy.finance/

<img width="659" alt="Screenshot 2022-09-02 at 09 54 29" src="https://user-images.githubusercontent.com/839848/188087194-16d3b388-a049-4023-aa49-5cd5264fd087.png">

**Comment by peetzweg** [comment]
This will be trickier than expected. We have to properly fetch the tokens per chain id was well. So we can't rely on the "currentChain" from useMidas/wagmi anymore.

**Comment by carlomazzaferro** [comment]
closing in favour of https://github.com/Midas-Protocol/monorepo/issues/464
