### ISSUE TITLE
Token Data is not Loaded Correctly when Chain is changed in a single session

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#601]
coming from BSC the token data looks good. Switching to polygon without a refresh, the token in the details of the polygon pool do not load correctly. A hard refresh  resolves this issue.

![demo](https://user-images.githubusercontent.com/839848/188174887-c4ae4d9a-c633-46af-817a-cc8f60f6b505.gif)

**Comment by smartdevcom** [comment]
https://github.com/Midas-Protocol/monorepo/pull/605
