### ISSUE TITLE
Revolve decimal issues when performing funding operations

### ISSUE THREAD

**Issue by carlomazzaferro** [Midas-Protocol/monorepo#606]
See the images below. Seems like the decimal issue still persists when calculation borrow limits, as well as the wallet balances

![Image](https://user-images.githubusercontent.com/9201443/188259949-83b1a801-d205-4910-b951-fae14a42c57c.png)
![Image](https://user-images.githubusercontent.com/9201443/188259953-6fe7ecf1-c4e8-4a5c-8fe2-1b15ddca30ff.png)

**Comment by smartdevcom** [comment]
issue is resolved
