### ISSUE TITLE
Use Hardcoded Override Asset Name Value in all Modals

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#615]
The token name listed in the supply/borrow columns is different than in the modal. 
This can be quite confusing. They should be the same.

![demo](https://user-images.githubusercontent.com/839848/188409833-61ca5266-52c6-4a1f-8a7f-19e2a9f4adf0.gif)

**Comment by smartdevcom** [comment]
PR https://github.com/Midas-Protocol/monorepo/pull/620
