### ISSUE TITLE
Expand `FusePools` Module Tests

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#618]
We should add a bit more elaborate tests to cover the issue we just fixed here:

https://github.com/Midas-Protocol/monorepo/pull/614

It needs to take proper mocked assets into account with varying decimals. Either in the Mocha tests or maybe better in the solidity hardhat tests to use also the contract logic.

It should prevent us from the future screwing up this calculation again.

https://github.com/Midas-Protocol/monorepo/blob/0bf47f28c9bfbb46e14c3fb0344e7dddd2ccc2ca/packages/sdk/tests-mocha/modules/FusePools.spec.ts#L12

**Comment by NikMidas** [comment]
No longer valid per Carlo and Peet
