### ISSUE TITLE
CSS Error in AmountSelect

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#641]
When opening the AmountSelect Modal on the PoolDetails page, I get this error on the console, can we resolve this?

`Using kebab-case for css properties in objects is not supported`

http://localhost:3000/137/pool/3

<img width="1218" alt="Screenshot 2022-09-08 at 11 36 10" src="https://user-images.githubusercontent.com/839848/189088895-a806b856-012b-4a64-a0f6-f9b059d7d110.png">

**Comment by carlomazzaferro** [comment]
Good one also for @adub671 !

**Comment by smartdevcom** [comment]
@peetzweg  Could you check this issue again? Because I couldn't see this issue anymore

**Comment by peetzweg** [comment]
Yes seems to be fixed. 👍
