### ISSUE TITLE
UI: Ability to sort APYs

### ISSUE THREAD

**Issue by NikMidas** [Midas-Protocol/monorepo#647]
![Image](https://user-images.githubusercontent.com/103433798/189360473-e59c40b0-81cd-440c-b411-b90541713d58.png)

**Comment by NikMidas** [comment]
Will wait for UI refactor

**Comment by NikMidas** [comment]
Per Alex and Peet, this is being reviewed as we speak

**Comment by smartdevcom** [comment]
PR https://github.com/Midas-Protocol/monorepo/pull/695
