### ISSUE TITLE
BUG: "Sending a transaction requires a signer" for certain functions

### ISSUE THREAD

**Issue by carlomazzaferro** [Midas-Protocol/monorepo#650]
![Image](https://user-images.githubusercontent.com/9201443/189477509-7c6d46e2-d506-4c4d-a717-ca534f918a75.png)

SDK refactoring issue: "Sending a transaction requires a signer". This has happened a few times in the SDK codebase after the initial multi-chain refactor -- we should double check how we are instantiating the SDK and the contracts, especially whenever a signer is needed.

**Comment by smartdevcom** [comment]
When did we get this issue? What action did user try?

**Comment by carlomazzaferro** [comment]
Myself, when trying to edit a pool and changing the "Borrowing Possibility"

The issue is that we're not passing the signer when using `sdk.createComptroller`

This is caused by the chain-agnostic refactoring that @peetzweg did

**Comment by peetzweg** [comment]
We should collect all admin actions here which cause this error to investigate further.
