### ISSUE TITLE
UI:  Add Discord and Gitbook Links in UI

### ISSUE THREAD

**Issue by NikMidas** [Midas-Protocol/monorepo#670]
![Image](https://user-images.githubusercontent.com/103433798/189921825-cdb3593a-b5bc-41c2-8f49-5b923c883979.png)

Gitbook: https://docs.midascapital.xyz/
Discord: https://discord.gg/85YxVuPeMt (links to Verify Here channel)

**Comment by smartdevcom** [comment]
PR https://github.com/Midas-Protocol/monorepo/pull/672
