### ISSUE TITLE
Some pool have flywheels without active markets

### ISSUE THREAD

**Issue by carlomazzaferro** [Midas-Protocol/monorepo#674]
Mai x DotDot x Midas pool (BSC):
![Image](https://user-images.githubusercontent.com/9201443/189988832-59dacf4d-39a1-4283-bd9d-b239456a975c.png)

MIMO pool(polygon):
![Image](https://user-images.githubusercontent.com/9201443/189988907-47076406-5e2a-47d3-99e6-7dccff3e06b3.png)

**Comment by peetzweg** [comment]
Related to this issue:
https://github.com/Midas-Protocol/monorepo/issues/233

**Comment by vminkov** [comment]
these are probably the old non-upgradable flywheels together with the new upgradable ones... no markets were added for rewards yet, that's possible

**Comment by carlomazzaferro** [comment]
> these are probably the old non-upgradable flywheels together with the new upgradable ones... no markets were added for rewards yet, that's possible

Actually, these are the newly deployed flywheels:

E.g. for dotddot: 
- https://github.com/Midas-Protocol/monorepo/blob/development/packages/sdk/deployments/bsc/MidasFlywheel_DDD.json 
- https://github.com/Midas-Protocol/monorepo/blob/development/packages/sdk/deployments/bsc/MidasFlywheel_EPX.json

These are clearly using the new plugins that were recently deployed as part of the upgrades

**Comment by vminkov** [comment]
> > these are probably the old non-upgradable flywheels together with the new upgradable ones... no markets were added for rewards yet, that's possible
> 
> Actually, these are the newly deployed flywheels:
> 
> E.g. for dotddot:
> 
> * https://github.com/Midas-Protocol/monorepo/blob/development/packages/sdk/deployments/bsc/MidasFlywheel_DDD.json
> * https://github.com/Midas-Protocol/monorepo/blob/development/packages/sdk/deployments/bsc/MidasFlywheel_EPX.json
> 
> These are clearly using the new plugins that were recently deployed as part of the upgrades

exactly, so we need to add the markets to the new flywheels
