### ISSUE TITLE
Replace Polygon RPC with New RPC

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#694]
When a user adds polygon freshly to their metamask we suggest an RPC url. 
The RPC we suggest seems to be quite limited and not working as good anymore.
We should replace it with some new RPC from https://chainlist.org/

<img width="1058" alt="Screenshot 2022-09-16 at 14 25 14" src="https://user-images.githubusercontent.com/839848/190638439-e685cc14-8fce-48e7-821a-8530dfeaa9c6.png">

**Comment by carlomazzaferro** [comment]
Yes, we should go with Ankr. It is already part of the user guides that Sev has been working on. https://github.com/Midas-Protocol/monorepo/commit/14d4acbc90451432d7c33a69771a4668fc9bd462
