### ISSUE TITLE
Several Images are not Shown in the production app

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#702]
Is this only for me? Have this since yesterday. We can host some of the icons oursevles if we fetch them from other services and run into limits.

<img width="622" alt="Screenshot 2022-09-20 at 11 50 28" src="https://user-images.githubusercontent.com/839848/191227022-1292f568-c7e4-407f-8cf8-e87b0b0defc2.png">
<img width="670" alt="Screenshot 2022-09-20 at 11 50 17" src="https://user-images.githubusercontent.com/839848/191227034-292888e2-3478-426b-b3f5-9471e3e49d12.png">
mart
<img width="273" alt="Screenshot 2022-09-20 at 11 50 08" src="https://user-images.githubusercontent.com/839848/191227039-87a247c4-5693-49c6-9b73-8e13bf738866.png">

**Comment by carlomazzaferro** [comment]
Seems like sushiswap removed their icons?

**Comment by carlomazzaferro** [comment]
https://raw.githubusercontent.com/sushiswap/icons/master/network/moonbeam.jpg

**Comment by carlomazzaferro** [comment]
Migrated here: https://github.com/sushiswap/list/tree/master/logos/network-logos @peetzweg @smartdevcom

**Comment by smartdevcom** [comment]
PR https://github.com/Midas-Protocol/monorepo/pull/703
