### ISSUE TITLE
Fix Open Graph Preview Image

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#704]
Not sure which metadata we need to set but this just looks sad.

We had tickets for this:
https://github.com/Midas-Protocol/monorepo/issues/82
https://github.com/Midas-Protocol/monorepo/pull/300

<img width="768" alt="Screenshot 2022-09-20 at 14 33 48" src="https://user-images.githubusercontent.com/839848/191258623-95a7b715-1da3-41a0-b45f-3e5fe9a92e2f.png">

**Comment by smartdevcom** [comment]
It seems like https://d1912tcoux65lj.cloudfront.net/social/social_midas.png doesn't work so it doesn't show image

**Comment by peetzweg** [comment]
@smartdevcom nice!
Wasn't aware that it's related to https://github.com/Midas-Protocol/monorepo/issues/702

Discord:
<img width="792" alt="Screenshot 2022-09-20 at 16 11 18" src="https://user-images.githubusercontent.com/839848/191280848-5e05b641-e51d-4a5a-9d81-4ba4b12e4b24.png">

Twitter:
<img width="865" alt="Screenshot 2022-09-20 at 16 15 36" src="https://user-images.githubusercontent.com/839848/191281908-2cb866e6-9ac3-4b44-9d04-74ae5f9d71c9.png">


Not too beautiful in iMessage and Telegram, quite sure it can be better. But I don't know what to set. Can we get it working in messengers as well?

iMessage:
<img width="337" alt="Screenshot 2022-09-20 at 16 10 58" src="https://user-images.githubusercontent.com/839848/191281088-80ff1544-d94c-4159-ab5e-4212eaf68846.png">

Telegram:
<img width="584" alt="Screenshot 2022-09-20 at 16 13 32" src="https://user-images.githubusercontent.com/839848/191281459-7a19591c-630f-4bf8-bb5d-7e4966248c30.png">

**Comment by smartdevcom** [comment]
I am not sure what I am missing but all were already set I guess

**Comment by smartdevcom** [comment]
The issue seemed to be related to image's size (it's recommended  under 100kb) so I changed its size smaller. Pls check again. In telegram, there might be cache issue as well

**Comment by smartdevcom** [comment]
Worked on telegram
![image](https://user-images.githubusercontent.com/45715420/191706219-0aa9af71-27e9-4f98-a1a6-09ba78e457fa.png)
