### ISSUE TITLE
FEATURE: Improvements of getting pools functions with pagination

### ISSUE THREAD

**Issue by smartdevcom** [Midas-Protocol/monorepo#720]
UI needs getting pools functions paginated from the SDK.

Actually 2 functions which get limited pools (i.e. 5 pools / a time)
 - pools that particular user uses
 - pools that particular user doesn't use

**Comment by peetzweg** [comment]
Not sure how well this ties into this cross chain topic.

https://github.com/Midas-Protocol/monorepo/issues/464

**Comment by peetzweg** [comment]
Not relevant anymore
