### ISSUE TITLE
Implement Feedback for Single Row Pool Details

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#723]
This issue mirrors collected feedback for the new Single Row Pool Details.

**Comment by peetzweg** [comment]
<img width="1029" alt="Screenshot 2022-09-23 at 10 35 12" src="https://user-images.githubusercontent.com/839848/191922439-47eca7d1-a6b4-4a32-99b9-6d4d9877a079.png">

**Comment by peetzweg** [comment]
<img width="993" alt="Screenshot 2022-09-23 at 10 36 58" src="https://user-images.githubusercontent.com/839848/191922513-8ffdabce-9719-4a66-9e3e-5a2f0ffcac20.png">

**Comment by smartdevcom** [comment]
> <img alt="Screenshot 2022-09-23 at 10 36 58" width="993" src="https://user-images.githubusercontent.com/839848/191922513-8ffdabce-9719-4a66-9e3e-5a2f0ffcac20.png">

Fixed

**Comment by smartdevcom** [comment]
> <img alt="Screenshot 2022-09-23 at 10 35 12" width="1029" src="https://user-images.githubusercontent.com/839848/191922439-47eca7d1-a6b4-4a32-99b9-6d4d9877a079.png">

Fixed
