### ISSUE TITLE
Ability to make a market "inactive"

### ISSUE THREAD

**Issue by carlomazzaferro** [Midas-Protocol/monorepo#732]
Some markets may become deprecated over time. "Unsupporting" them is most times not doable because if there is any dust in them, they cannot be removed.

The only solution is to make it inactive in the UI, greying it out. This disables depositing anything to that market, but withdrawing it should still be possible. 

For assets that are also borrowable, repaying the borrows should also be possible. 

Main use-case: 2brl on BSC should be marked as inactive

**Comment by carlomazzaferro** [comment]
This already exists on the CToken: pausing borrowing and minting. 

I suppose what we can do: if the borrowing and minting is paused, the UI should reflect that: greyed out, only repaying loans and withdrawing is possible. Hows that sound?

**Comment by peetzweg** [comment]
Yes thats the way to go. 
I'm sure we are already fetching this information if this is paused. @smartdevcom correct me if I'm wrong.

Maybe we can introduce a new badge like "Reward", "Collateral" etc. 
Called "Deprecated" or "Lecacy"? And only show the tag if the comptroller contains markets with ctoken which have minting disabled. This way we still show the market, so people can withdraw their tokens via the UI still.

Even better would be to just show this "Deprecated" market only to these users which have a "supply" still left in this market. So for new users to this Pool the "Legacy" market is not visible at all. But for users which have a supply still left in this "legacy" market they can still see it until they withdraw their full balance from it. So only show if the user has balance in the market, not if the overall market has any supply left.

**Comment by smartdevcom** [comment]
I am sure we could check borrowing paused. And how to check supplying paused? Did we have property on asset something like `isSupplyingPaused`? cc @carlomazzaferro

**Comment by carlomazzaferro** [comment]
So, it seems like we need to edit the FusePoolLens.sol to return this data:

Here: https://github.com/Midas-Protocol/contracts/blob/development/contracts/FusePoolLens.sol#L364-L365

we need to add:

```
asset.mintGuardianPaused = comptroller.mintGuardianPaused(address(cToken));
```

And then pass this back to the SDK. Will add this as a task for this tickent

> I am sure we could check borrowing paused. And how to check supplying paused? Did we have property on asset something like `isSupplyPaused`? cc @carlomazzaferro

**Comment by carlomazzaferro** [comment]
Tasks:

- [ ] Add mint guardian paused status to the FusePoolLens returned data
- [ ] Add such field in the SDK
- [ ] Implement UI features: if borrowing and minting are paused, asset is marked as "deprecated", which shows it as grayed out, and only repaying borrows / withdrawing liquidity is allowed

**Comment by smartdevcom** [comment]
Got it

**Comment by smartdevcom** [comment]
Ah, we already got 'isSupplyPaused` in asset

**Comment by carlomazzaferro** [comment]
> isSupplyPaused

Good catch! We can use that
