### ISSUE TITLE
BUG: max withdrawal and borrow still dysfunctional in Neon Dev Net

### ISSUE THREAD

**Issue by carlomazzaferro** [Midas-Protocol/monorepo#733]
See: https://discord.com/channels/930077813585899561/973139614942527499/1023201255285329950

**Comment by peetzweg** [comment]
Regarding max withdrawal. It's now fixed on the contract side and has a new way of withdrawing the max amount. A pr adapting the use in the frontend is in review.

Check Ticket https://github.com/Midas-Protocol/monorepo/issues/431#issuecomment-1252293059

PR: https://github.com/Midas-Protocol/monorepo/pull/722

**Comment by peetzweg** [comment]
Just read your discord message, not sure if this resolves this. But Yes will check again. Seems a bit odd your case.
