### ISSUE TITLE
Don't Show Rewards which are not Distributed Anymore

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#737]
As static rewards became relevant today it came to mind, that we should make sure we don't show fw rewards which are not distributed anymore because their distribution period ended.

https://github.com/fei-protocol/flywheel-v2/blob/5ac5d314362188e3ece31a9db7deba529f4e8cc7/src/rewards/FlywheelStaticRewards.sol#L14-L20

<img width="667" alt="Screenshot 2022-09-26 at 11 28 09" src="https://user-images.githubusercontent.com/839848/192242289-756c9eee-f643-461f-8278-e2058f2ec8b0.png">

**Comment by peetzweg** [comment]
<img width="1454" alt="Screenshot 2022-10-03 at 10 42 03" src="https://user-images.githubusercontent.com/839848/193535781-7fb9c0ed-c993-45aa-9413-cc9303206abf.png">

<img width="1419" alt="Screenshot 2022-10-03 at 10 41 03" src="https://user-images.githubusercontent.com/839848/193535789-8341787f-b71a-4d02-842e-01fbc5faa944.png">

**Comment by smartdevcom** [comment]
Seems like it was fixed by this PR https://github.com/Midas-Protocol/monorepo/issues/461
