### ISSUE TITLE
Remove Duplicated Definitions in ABIs

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#739]
Clear out these duplicated definitions from the ABI definitions? It think it's duplicated in the ABI. Not sure though. It spams the browser console and thereby also impacting performance a bit aside of being annoying.

<img width="882" alt="Screenshot 2022-09-26 at 17 06 24" src="https://user-images.githubusercontent.com/839848/192313194-3f5d65c0-c22c-4090-ad97-51a310357f99.png">

**Comment by carlomazzaferro** [comment]
completed by @vminkov
