### ISSUE TITLE
Change MAX Label on Borrow / Borrow Max, does not Borrow Max Possible Amount

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#74]
## Background

When I click the `MAX` Button while borrowing, I expect to borrow the maximum I'm allowed to borrow with my current supplied collateral. This does not seem to be the case. Is this intended?

## Demonstration

![demo2](https://user-images.githubusercontent.com/839848/169254704-b26736f1-e5c8-4841-ba63-7a7f850daa36.gif)

**Comment by Pczek** [comment]
This is intended behaviour, however it would be cool to change the label of the `MAX` Button to `75%`.

https://github.com/Midas-Protocol/monorepo/blob/d1749c137a2e08c030675234d3ed6f9af1d40c8b/packages/ui/components/pages/Fuse/Modals/PoolModal/AmountSelect.tsx#L808-L812
