### ISSUE TITLE
Add ability to copy address, or alternatively go to block explorer URL on Pool Addresses

### ISSUE THREAD

**Issue by carlomazzaferro** [Midas-Protocol/monorepo#743]
Instead of having either the address alone, eg:

![Image](https://user-images.githubusercontent.com/9201443/192326417-bbf2e5c7-c702-4793-936c-fff6a3226012.png)

Or the (click to copy):

![Image](https://user-images.githubusercontent.com/9201443/192326522-a0d348bd-43ac-48b5-a232-406267e32951.png)

We should standardise this, as such:

![Image](https://user-images.githubusercontent.com/9201443/192326324-41b8860d-ee20-4927-bb70-74f5c1cc3546.png)

- [ ] When clicking on the address, open a new tab with the block explorer address
- [ ] When clicking on the icon to copy, copy the address to clipoard

**Comment by peetzweg** [comment]
But let's not make it red okay? 😂

**Comment by carlomazzaferro** [comment]
> But let's not make it red okay? 😂

oh boy, please no

**Comment by smartdevcom** [comment]
![image](https://user-images.githubusercontent.com/45715420/192432769-c7a46cef-afa2-4603-be7f-88ab64e3e9d4.png)
![image](https://user-images.githubusercontent.com/45715420/192432814-6335e04c-f6d0-429a-afad-600d77097e0b.png)
