### ISSUE TITLE
Missing Reward Badge for Markets with Flywheel Only Rewards

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#767]
We've just added a Flywheel with Static Rewards to the Jarvis Pool on Polygon. It's distributing rewards per seconds. The Market should also be marked with the `Rewards` Badge.

Furthermore the Token Tooltip is on hover of the JRT icon is not working and the icon is not aligned  vertically with the text.

<img width="1436" alt="Screenshot 2022-10-03 at 10 35 53" src="https://user-images.githubusercontent.com/839848/193548362-2365ab6f-bb17-4d2b-be2c-942da927dc4e.png">

**Comment by peetzweg** [comment]
The "Rewards" badge is only added if there are any rewards to be claimed. So once some rewards accumulate for you to be claimed it has the "Rewards" badge. Seems logical but a bit confusing for sure. Let's think about how to possibly improve this. If necessary.

Is this correct @smartdevcom ?

**Comment by smartdevcom** [comment]
Yes, this badge should be shown if asset has claimable rewards

it's check like this 

`const { data: claimableRewards } = useAssetClaimableRewards({
    poolAddress,
    assetAddress: asset.cToken,
  });`

`export const useAssetClaimableRewards = ({
  poolAddress,
  assetAddress,
}: {
  poolAddress: string;
  assetAddress: string;
}) => {
  const { currentSdk, address } = useMultiMidas();

  return useQuery<FlywheelClaimableRewards[] | undefined>(
    ['useAssetClaimableRewards', poolAddress, assetAddress, address, currentSdk?.chainId],
    () => {
      if (currentSdk && address)
        return currentSdk.getFlywheelClaimableRewardsForAsset(poolAddress, assetAddress, address);
    },
    { enabled: !!poolAddress && !!address && !!currentSdk }
  );
};`

**Comment by smartdevcom** [comment]
Are we new calculating to claim static rewards?

**Comment by smartdevcom** [comment]
I just changed the style, not resolved all of this issue, shouldn't we reopen this issue? cc @peetzweg
