### ISSUE TITLE
Expand Plugin APY Tooltip if APY is available

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#769]
It would be nice to have the tooltip to the beefy vault expand over to the APY number as well. So we show people where the APYs are coming from. People might miss it if they only hover over the number and not the plugin.

![demo](https://user-images.githubusercontent.com/839848/193553430-137fafad-52d3-48d2-aa0d-953e499d4916.gif)

**Comment by smartdevcom** [comment]
PR https://github.com/Midas-Protocol/monorepo/pull/774
