### ISSUE TITLE
Include Plugin APYs in When Sorting

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#783]
We should include the APYs from Plugins into the sorting algorithm.

<img width="1439" alt="Screenshot 2022-10-04 at 17 39 29" src="https://user-images.githubusercontent.com/839848/193864001-c14321b0-a5c2-4b54-8c00-e99d2c7305a5.png">

**Comment by smartdevcom** [comment]
https://github.com/Midas-Protocol/monorepo/pull/785
