### ISSUE TITLE
Prevent Flickering on Navigation

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#796]
Navigating Back and forth between a pool and the pool list the filter jumps from All Pools to the previously selected chain.
It's okay but would be nicer if it would not do it.
Probably need to optimize how e get this data and store it in a context so it directly available instead of fetching it from the localStorage. It still needs to be in the local storage to persist it though.

![demo](https://user-images.githubusercontent.com/839848/194344067-091be595-8ba2-43b6-8800-b2663ebbf55b.gif)

**Comment by smartdevcom** [comment]
To fixed this issue, I think some prefetch data should be passed to `PoolsRowList` directly without initial data. like this https://github.com/Midas-Protocol/monorepo/pull/751#discussion_r988837215, wdyt?

**Comment by peetzweg** [comment]
For sure it's improved 👍 
Not yet perfect but fine for me already. 

Try spamming `CMD + R` to refresh super often, it will show this behaviour.


![demo](https://user-images.githubusercontent.com/839848/194527799-4f14c838-ed0f-458b-a172-682cfae3a890.gif)

**Comment by peetzweg** [comment]
Maybe the disconnected buttons happen as it's thinking it's on mobile first? Or maybe this is the default style? 

I think we should use the connected buttons onmobile as well but only the network images. To get it on a single row.

![IMG_4795](https://user-images.githubusercontent.com/839848/194530030-c522df24-7845-4e84-90f8-14836bf67c2c.PNG)

**Comment by smartdevcom** [comment]
Above 2 issues are fixed, PR is ready
