### ISSUE TITLE
UI: Improvements For New UI

### ISSUE THREAD

**Issue by NikMidas** [Midas-Protocol/monorepo#802]
UI improvements:
- when i click a chain symbol to toggle the pool id expect it to only show that chain, but instead it toggles to only exclude that chain.
- while loading pools it shouldnt say "No pools found", it should show a skeleton loader
- if i click the back button it should store my filters (suggest putting this in URL param instead of cookie)

per https://discord.com/channels/930077813585899561/1026831118768549939/1027189980323381328

**Comment by peetzweg** [comment]
Duplicated of https://github.com/Midas-Protocol/monorepo/issues/786
✅
