### ISSUE TITLE
Add Open Graph Data and Images for Midas Dapp Preview Links

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#82]
Would be great if we could add Open Graph Data to the Dapp, so web messengers and websites can show some preview information about midas, being more pleasing than a plain link.

We need some images we could show. Later we could potentially generate an image for the pool which was shared on the fly.

The more info we have the better:
https://ogp.me/

How to check:

https://www.opengraph.xyz/url/https%3A%2F%2Fmarket.xyz/

https://dnschecker.org/open-graph-preview-generate-metatags.php?query=development--midas-capital-dapp.netlify.app

![Image](https://user-images.githubusercontent.com/839848/169771891-814c7b0a-fc44-409d-a32d-7e0ca496c27f.png)

**Comment by peetzweg** [comment]
Asked about this in the #marketing channel, `Manisha | Marketing#2455` seems to take care of the assets for this. 
https://discord.com/channels/930077813585899561/961312232350818314/980848539619971152

**Comment by smartdevcom** [comment]
We need more info to show it in facebook and twitter.
Needed:
1) Title
2) Description
