### ISSUE TITLE
Directly set deposit limits in the pool operator UI

### ISSUE THREAD

**Issue by NikMidas** [Midas-Protocol/monorepo#820]
Add the functionality to directly set deposit limits in the pool operator UI, limits should probably be done in the amount of actual asset and not dollar terms to make sure these aren't flashloan attackable

**Comment by NikMidas** [comment]
This is prioritized over https://github.com/Midas-Protocol/monorepo/issues/477

**Comment by peetzweg** [comment]
I think it would fit well here. It's nice to now but does not have to be prominently displayed.

<img width="1433" alt="Screenshot 2022-11-07 at 15 09 51" src="https://user-images.githubusercontent.com/839848/200330837-8d7ce4f8-1933-41ae-ad0f-cede5a238d9f.png">
