### ISSUE TITLE
Prevent Fetching Interest Rate Modal Graph for Protected Assets

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#828]
The protected assets should don't show any interest rate model graphs, so we should even prevent them from loading them.

![demo](https://user-images.githubusercontent.com/839848/195016244-bebafcbb-f53c-4f91-85d4-1d034f30d070.gif)

**Comment by smartdevcom** [comment]
Fixed here https://github.com/Midas-Protocol/monorepo/pull/826
