### ISSUE TITLE
Amount Max Button does set the Correct Amount

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#84]
We now have two tickets which seem to be related to the same issue. The `MAX` button in the Amount modal, is not setting the correct amount. Either during Supply, Borrow and Repay. Probably also during withdraw.

See these tickets for more info:
Related: #74 #25

**Comment by Pczek** [comment]
Both issues are not related as I thought.

**Comment by dezine2dev** [comment]
These issues are separated and addressed in two PRs individually
https://github.com/Midas-Protocol/monorepo/pull/132
https://github.com/Midas-Protocol/monorepo/pull/131
