### ISSUE TITLE
Upgrade to React 18 / Chakra UI 2

### ISSUE THREAD

**Issue by Pczek** [Midas-Protocol/monorepo#86]
Next 12 does support React 18. Also the new chakra ui version requires React 18 and is not compatible anymore.

I tried using it but running into `hydration mismatch` exceptions.

It does not point out the component. Basically our whole app should be rendered client side. Might be tricky to resolve these.

**Comment by smartdevcom** [comment]
It was blocked but Chakra UI v2 seems to be working properly with yarn installing. so merged, Done
