### ISSUE TITLE
Show Strategy Risk Score

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#865]
Needs https://github.com/Midas-Protocol/monorepo/pull/660 to be merged:

The new `@midas-capital/security` package brings access to a hardcoded risk score for our ERC4626 strategies. We should show this Risk score somehow in the UI.

It could be on the Strategy APY tooltip itself and a more detailed version in the market details drop down.

The detailed view can should be inspired by Beefy`s strategy score.

https://app.beefy.finance/vault/sicle-btc.b-wavax

<img width="957" alt="Screenshot 2022-10-18 at 12 05 52" src="https://user-images.githubusercontent.com/839848/196401311-538e634c-28f7-4731-bc59-8a93981a313d.png">

**Comment by peetzweg** [comment]
Just added the new `security` package from carlo:
https://github.com/Midas-Protocol/monorepo/pull/660


We can now add strategy risk scoring to the tooltip itself and the market details dropdown.
<img width="794" alt="Screenshot 2022-10-21 at 12 14 35" src="https://user-images.githubusercontent.com/839848/197172728-d585543e-c4b2-4d62-b155-0c9c9be8e9c2.png">
<img width="1519" alt="Screenshot 2022-10-21 at 12 13 40" src="https://user-images.githubusercontent.com/839848/197172742-2048f585-6801-40b2-a8c6-2a7923334796.png">

**Comment by carlomazzaferro** [comment]
I will also add a documentation page for it on the midas docs. There should be a place for a link to our docs

**Comment by carlomazzaferro** [comment]
@peetzweg this is the docs link to be used: https://docs.midascapital.xyz/security/security-outline/4626-strategy-risk-scoring
