### ISSUE TITLE
Only Show Liquidity of Borrowable Assets

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#873]
The Liquidity Popover shows also protected assets. Which does not make sense. 
Liquidity is only of interest for assets which are borrowable. So we should excluded protected assets in this popover list.

<img width="1425" alt="Screenshot 2022-10-19 at 16 12 45" src="https://user-images.githubusercontent.com/839848/196726581-c3398aa9-ec1b-4f72-bd7a-7f2212ae91e3.png">

**Comment by smartdevcom** [comment]
Shouldn't we also hide liquidity amount for `protected assets` ?

![image](https://user-images.githubusercontent.com/45715420/196837482-e28eff83-b9c2-48ef-93ac-a8018789edf0.png)
