### ISSUE TITLE
Task to periodically check and redeem accrued borrow and 4626 fees

### ISSUE THREAD

**Issue by carlomazzaferro** [Midas-Protocol/monorepo#895]
let's check if we actually make money, and take that money

**Comment by peetzweg** [comment]
How to do this? What are our income streams and how to check them?

**Comment by carlomazzaferro** [comment]
> How to do this? What are our income streams and how to check them?

ERC4626 fees:
https://github.com/Midas-Protocol/contracts/blob/development/contracts/midas/strategies/MidasERC4626.sol#L144
Need to verify how we set the fee receiver if not initialised, but that's the bottom line

FuseFees (liquidations and borrow fees):

```
function getPendingFuseFeeFromAdmin() internal view returns (uint256) {
    return IFuseFeeDistributor(fuseAdmin).interestFeeRate();
  }
```

In CToken.sol

So we'll need to think of a good way to query them all
