### ISSUE TITLE
Add link to feature request platform

### ISSUE THREAD

**Issue by carlomazzaferro** [Midas-Protocol/monorepo#911]
A button taking you to https://midascapital.canny.io/feature-requests should be added in the bottom left area of our page.

![Image](https://user-images.githubusercontent.com/9201443/198267560-eecb3195-b4ba-45fc-82a8-ff9be7275a1d.png)

See https://www.matcha.xyz/markets/1/ETH for inspiration

**Comment by peetzweg** [comment]
I would even go as far as to move it to the front page super prominently. So users are actually aware that we are happy to receive suggestions 📈 

<img width="1042" alt="Screenshot 2022-10-27 at 13 22 34" src="https://user-images.githubusercontent.com/839848/198271585-26aee3df-796f-4894-903b-9d9f90bc9d27.png">

**Comment by carlomazzaferro** [comment]
> I would even go as far as to move it to the front page super prominently. So users are actually aware that we are happy to receive suggestions 📈 
> 
> <img width="1042" alt="Screenshot 2022-10-27 at 13 22 34" src="https://user-images.githubusercontent.com/839848/198271585-26aee3df-796f-4894-903b-9d9f90bc9d27.png">
> 

Good idea!

**Comment by peetzweg** [comment]
<img width="1473" alt="Screenshot 2022-10-28 at 09 49 37" src="https://user-images.githubusercontent.com/839848/198533673-cc7ee2fa-c687-43ea-a928-8b6654955f5b.png">

Use no icon, people will not know what it means. Should be a link to 
`https://midascapital.canny.io/feature-requests`
