### ISSUE TITLE
Rework Flywheel Static Rewards UX

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#924]
The current implementation of the Flywheel Static Rewards has some disasters which could happen.

+ rewards get distributed even when the flywheel is empty
+ if end timestamp is reached it stops, if this value is then updated to be in the future again, users would accrue in the "off-time" of the flywheel again, so flywheel can not be reused.

**Comment by NikMidas** [comment]
This ticket as written is not valid
