### ISSUE TITLE
Common way of displaying APYs for yield bearing tokens (mostly LSD tokens)

### ISSUE THREAD

**Issue by NikMidas** [Midas-Protocol/monorepo#932]

**Comment by peetzweg** [comment]
We need endpoints from partners to get their APYs similar as we do for strategies.

**Comment by peetzweg** [comment]
As of now it's hardcoded which is not good.

https://github.com/Midas-Protocol/monorepo/blob/7f226dc4a96b9e82cf7fb3c96822c695748f8e08/packages/ui/components/pages/Fuse/FusePoolPage/MarketsList/SupplyApy.tsx#L68-L97

**Comment by peetzweg** [comment]
Related https://github.com/Midas-Protocol/monorepo/issues/1020
