### ISSUE TITLE
Add support for DeFiLlama yield dashboard

### ISSUE THREAD

**Issue by NikMidas** [Midas-Protocol/monorepo#933]
- Add Ankr rewards token to WBNB yield

**Comment by peetzweg** [comment]
cc @smartdevcom 
It's great to have the markets on defi lama!

As we are using the /public/rewards enpdoint it's including the rewards APY from strategies. This endpoint does not respond with information about rewards from "Liquidity Mining Programs" aka static rewards from flywheels. 
These APYs change so fast, that we decided to just fetch them on chain via the a FusePoolLens call.

https://github.com/Midas-Protocol/monorepo/blob/ec13b1616bfb08c142f5d5e1d3bd17f46f5bfa05/packages/ui/hooks/useRewards.ts#L32-L35

We should make this call as well in the Defi lama adapter. We could move it into the `/public/rewards`  endpoint as well but there we don't have access to a provider, so in the llama adapter is probably the easiest.

<img width="748" alt="Screenshot 2023-02-14 at 14 17 21" src="https://user-images.githubusercontent.com/839848/218750516-8093627e-31cc-4de7-8e8b-145d02cc5a68.png">
<img width="748" alt="Screenshot 2023-02-14 at 14 16 41" src="https://user-images.githubusercontent.com/839848/218750531-12bfc1b8-6d9f-4242-835b-98b17abc11b7.png">

**Comment by smartdevcom** [comment]
fixed!
