### ISSUE TITLE
Add support for Zapper.fi via Zapper Studio

### ISSUE THREAD

**Issue by NikMidas** [Midas-Protocol/monorepo#944]
Per Manisha's message from Zapper:

![Image](https://user-images.githubusercontent.com/103433798/199561416-e4f39ca5-0fa3-4fd5-9b3c-5ca2a8f19539.png)

Build on Zapper | Build on Zapper
Zapper Studio documentation.

Integration documentation: https://studio.zapper.fi

Github repo: https://github.com/Zapper-fi/studio

Integration channel on Discord: https://discord.com/channels/647279669388771329/964569348243075082"

**Comment by peetzweg** [comment]
@smartdevcom can you share the PR here for to the Zapper Studio repo, thanks! :)

**Comment by smartdevcom** [comment]
I opened PR and they will review it https://github.com/Zapper-fi/studio/pull/1671

**Comment by NikMidas** [comment]
No response from the third party yet

**Comment by carlomazzaferro** [comment]
Done!
