### ISSUE TITLE
Website in not Loading due to Favicon?!

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#965]
Getting infinite loading when a favicon can not be loaded?!

Only a fresh helps. This sucks. Seams to happen very seldom though. But has happened more and more. Not sure why. Need to observe this.

<img width="1800" alt="Screenshot 2022-11-04 at 14 24 41" src="https://user-images.githubusercontent.com/839848/199983606-f942ea40-6471-4e8a-9da4-82193c52b480.png">
<img width="1799" alt="Screenshot 2022-11-04 at 14 24 08" src="https://user-images.githubusercontent.com/839848/199983610-5f9f042f-f4fd-4707-8d4d-b628fc6cf524.png">

**Comment by smartdevcom** [comment]
Is this right? I guess it's not loaded because of usdPrice? On my side, I couldn't reproduce it and didn't see the case often except the case I couldn't usdPrice properly
