### ISSUE TITLE
Confirm Entering Liquidation Range

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#986]
We want to have users explicitly have to confirm if they borrow and entering a loan to value ratio which is considered high. So if a user has a borrow limit of 1000 USD and will enter a total borrow of 80% with the current borrow in the Amount Modal we want to have an extra layer in the UI to ask the user to confirm that he is aware that they are likely to get liquidated.

I think a checkbox would be good as a start. The user has to check the checkbox to enable the `borrow` button again when entering 80% of total borrow.

- [ ] I'm aware that I'm entering >80% of my borrow limit and thereby have a high risk of getting liquidated.

**Comment by NikMidas** [comment]
@smartdevcom already completed and in review
