### ISSUE TITLE
Reduce Deployments JSON File Size

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#992]
As we already refactor the SDK parts a bit we can have a big bundle size reduction if we remove the `abi` and if applicatable the `deployed_bytecode` from the JSON file. The only thing we rely on from the `deployments.json` files are the actual addresses of the contracts.

**Comment by peetzweg** [comment]
+1 for the flywheels stuff

**Comment by NikMidas** [comment]
Per @peetzweg, please refine this ticket with more info to be worked

**Comment by peetzweg** [comment]
<img width="1797" alt="Screenshot 2023-01-18 at 15 54 54" src="https://user-images.githubusercontent.com/839848/213204298-ae0b77df-4ada-4595-9b83-14a9db1dece5.png">

As assumed, the chain.json files are the biggest chunk of our current frontend bundle. We need to clean them asap and can probably save up to 1/3 of the bundle size.
