### ISSUE TITLE
Fix LogRocket

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#995]
We don't get any Log Rocket messages anymore. 
Furthermore we need to send everything we can to logrocket, something is broken for sure rn.

<img width="874" alt="Screenshot 2022-11-11 at 10 25 59" src="https://user-images.githubusercontent.com/839848/201309403-09ca341e-012b-42b1-ad81-fcad91e523d4.png">

**Comment by smartdevcom** [comment]
Check this cc @peetzweg 
![image](https://user-images.githubusercontent.com/45715420/202056343-a7449f56-f5d8-4920-8332-bef6374a4d54.png)
![image](https://user-images.githubusercontent.com/45715420/202056423-539259da-f66b-4c46-8ee5-65d3e5baa6fb.png)

It seems like recorded data already exceeded limit amount of our plan. 
It will reset on `11-20-2022` I guess

**Comment by peetzweg** [comment]
Will check if paying makes sense or we switch to another service with a more generous free tier.

**Comment by peetzweg** [comment]
@smartdevcom are we sure it's disabled in development?
Can only use it in Production production. So on app.midascapital.xyz?

Maybe we can also reduce some logs we make, some tracking events. 
If we are sure it's not logging in development we can check how far we get in December with the free tier and upgrade if necessary.

**Comment by peetzweg** [comment]
Added a commit to just init it if an `LOGROCKET_APP_ID` is set. Which I setup on netlify direclty only for production, so it should be only working in production, skipping development and preview. Can be debug however on localhost if var is used.

**Comment by peetzweg** [comment]
Let's leave this Ticket open for now and check how far we get in December.

**Comment by carlomazzaferro** [comment]
Not that far it seems 🥲

I suppose we can turn off the session recording / logging?

![Screenshot_20221123-085711.png](https://user-images.githubusercontent.com/9201443/203496241-4336ef92-a85e-4d62-8556-b089fab3ba3c.png)

**Comment by peetzweg** [comment]
Fail... setting an env var on netlify is not available in the bundle set to the client obviously. 🙈
Classic mistake. Let me think about another way to toggle this only in production haha.


<img width="1042" alt="Screenshot 2022-11-24 at 12 48 13" src="https://user-images.githubusercontent.com/839848/203777346-98ae986b-237e-4ebd-9f7f-b242fe657955.png">


@carlomazzaferro will dive into the settings to see what we can deactivate to extend this. I thought it will be reset every starting month. Unhandy that it is using a rolling window. :S

**Comment by peetzweg** [comment]
Now it should only be in production 🤞 :D
https://github.com/Midas-Protocol/monorepo/commit/b05e7dff5c4049f6270d7ba241a1b13333a5fc6a

**Comment by NikMidas** [comment]
Completed for now, will review in Dec 2022
